import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';
test('plugins consume static manifests and host has no Factory discovery endpoint',async()=>{const nam=await readFile('src/nam-wam/gui.js','utf8'),cab=await readFile('src/cabinet-wam/gui.js','utf8'),host=await readFile('examples/wam/main.js','utf8');assert.match(nam,/models-manifest\.json/);assert.match(cab,/irs-manifest\.json/);assert.doesNotMatch(host,/models-manifest|irs-manifest|api\/.*(model|ir)/);});
test('host requests the NAM-compatible 48 kHz audio context',async()=>{const host=await readFile('examples/wam/main.js','utf8');assert.match(host,/new AudioContext\(\{\s*latencyHint:\s*'interactive',\s*sampleRate:\s*48000\s*\}\)/u);assert.match(host,/context\.sampleRate !== 48000/u);});
test('slimmable A2 renderer exposes an explicit Full/Lite selector',async()=>{const [wrapper,processor,node,cmake]=await Promise.all(['src/nam-wasm/nam_wrapper.cpp','src/nam-wam/NamProcessor.js','src/nam-wam/NamNode.js','CMakeLists.txt'].map((path)=>readFile(path,'utf8')));assert.match(wrapper,/nam_set_slimmable_size/u);assert.match(processor,/variant === 'lite' \? 0 : 1/u);assert.match(node,/setModelVariant\(variant\)/u);assert.match(cmake,/_nam_set_slimmable_size/u);});
test('model loudness compensation is applied separately from manual output gain',async()=>{const [processor,node]=await Promise.all(['src/nam-wam/NamProcessor.js','src/nam-wam/NamNode.js'].map((path)=>readFile(path,'utf8')));assert.match(processor,/this\._ready \? this\._wasmOutput\[i\] \* this\._normalizationCurrent : output\[n\]/u);assert.match(processor,/const meteredOutput = processedOutput \* gain/u);assert.match(processor,/this\._normalizationCurrent \+= \(this\._normalizationTarget - this\._normalizationCurrent\) \* 0\.005/u);assert.match(node,/modelLevelCompensationDb\(metadata\.loudness, this\._autoLevel\)/u);});

test('NAM tone, gate, and six-band EQ mirror the official plugin routing defaults',async()=>{const processor=await readFile('src/nam-wam/NamProcessor.js','utf8');for(const id of ['noise','noiseEnabled','bass','middle','treble','toneEnabled','eqEnabled','eqPre'])assert.match(processor,new RegExp(`new WamParameterInfo\\('${id}'`));for(let i=1;i<=6;i++)for(const suffix of ['Freq','Gain','Q'])assert.match(processor,new RegExp(`eq${i}${suffix}`));assert.match(processor,/_processGateSample\(meteredInput\)/u);assert.match(processor,/if \(eqIsPre\) \{/u);assert.match(processor,/if \(eqEnabled\) processedInput = this\._processEqSample/u);assert.match(processor,/if \(!eqIsPre\) \{/u);assert.match(processor,/if \(eqEnabled\) processedOutput = this\._processEqSample/u);assert.match(processor,/if \(toneEnabled\) processedOutput = this\._processToneSample/u);});

test('all tone-shaping controls participate in the standard WAM state round trip',async()=>{const [processor,node]=await Promise.all(['src/nam-wam/NamProcessor.js','src/nam-wam/NamNode.js'].map((path)=>readFile(path,'utf8')));const ids=['inputGain','outputGain','noise','noiseEnabled','bass','middle','treble','toneEnabled','eqEnabled','eqPre','bypass'];for(let i=1;i<=6;i++)for(const suffix of ['Freq','Gain','Q'])ids.push(`eq${i}${suffix}`);for(const id of ids)assert.match(processor,new RegExp(`new WamParameterInfo\\('${id}'`),`missing WAM state parameter ${id}`);assert.match(node,/const parameterState = await super\.getState\(\)/u);assert.match(node,/parameterValues: parameterState\.parameterValues/u);assert.match(node,/await super\.setState\(\{parameterValues: state\.parameterValues \|\| \{\}\}\)/u);assert.match(node,/stateVersion: 5/u);});

test('noise gate is off by default while remaining a saved WAM parameter',async()=>{const processor=await readFile('src/nam-wam/NamProcessor.js','utf8');assert.match(processor,/noiseEnabled: new WamParameterInfo\('noiseEnabled', \{type:'boolean', label:'Noise Gate Enabled', defaultValue:0\}\)/u);});

test('EQ is enabled by default and can still be bypassed through WAM state',async()=>{const [processor,gui]=await Promise.all(['src/nam-wam/NamProcessor.js','src/nam-wam/gui.js'].map((path)=>readFile(path,'utf8')));assert.match(processor,/eqEnabled: new WamParameterInfo\('eqEnabled', \{type:'boolean', label:'Parametric EQ Enabled', defaultValue:1\}\)/u);assert.match(gui,/class="eqEnabled" type="checkbox" checked/u);assert.match(gui,/this\.controls\.eqPanel\.classList\.toggle\('is-off',!enabled\)/u);});

test('graphical EQ exposes colored band responses and a comparative spectrum analyzer',async()=>{const [processor,node,gui]=await Promise.all(['src/nam-wam/NamProcessor.js','src/nam-wam/NamNode.js','src/nam-wam/gui.js'].map((path)=>readFile(path,'utf8')));assert.match(processor,/SPECTRUM_FFT_SIZE = 2048/u);assert.match(processor,/SPECTRUM_BINS = 64/u);assert.match(processor,/_analyzeSpectrum\(this\._spectrumInputRing, this\._spectrumInputBins\)/u);assert.match(processor,/_analyzeSpectrum\(this\._spectrumFilteredRing, this\._spectrumFilteredBins\)/u);assert.match(processor,/_analyzeSpectrum\(this\._spectrumFinalRing, this\._spectrumFinalBins\)/u);assert.match(processor,/if \(eqIsPre\)/u);assert.match(node,/setSpectrumEnabled\(enabled\)/u);assert.match(gui,/EQ_BAND_COLORS/u);assert.match(gui,/class="eq-spectrum"/u);assert.match(gui,/class="eq-spectrum-input-line"/u);assert.match(gui,/class="eq-spectrum-filtered-line"/u);assert.match(gui,/class="eq-spectrum-final-line"/u);assert.match(gui,/class="eqBandCurves"/u);assert.match(gui,/addSpectrumListener/u);assert.match(gui,/setSpectrumEnabled\(this\._editorVisible!==false&&this\._activePluginTab==='amp'\)/u);});

test('optional measured level calibration probes and resets the active NAM model',async()=>{const [processor,node]=await Promise.all(['src/nam-wam/NamProcessor.js','src/nam-wam/NamNode.js'].map((path)=>readFile(path,'utf8')));assert.match(processor,/data\.namRequest === 'calibrate'/u);assert.match(processor,/CALIBRATION_WARMUP_FRAMES/u);assert.match(processor,/CALIBRATION_MEASURE_FRAMES/u);assert.match(processor,/nam_reset\(this\._namHandle\)/u);assert.match(node,/async calibrateModelLevel\(\)/u);assert.match(node,/async applyMeasuredModelLevel\(calibration\)/u);assert.match(node,/levelMode:'measured'/u);});
test('factory manifest entries use path identities and concise rich-bundle groups',async()=>{const m=JSON.parse(await readFile('src/nam-wam/models-manifest.json')),i=JSON.parse(await readFile('src/cabinet-wam/irs-manifest.json'));for(const a of [...m.assets,...i.assets]){assert.equal(a.id,`factory:${a.relativePath}`);assert.equal(a.relativePath.includes('\\'),false);assert.deepEqual(a.groups,a.provenance?.title?[a.provenance.title]:a.relativePath.split('/').slice(0,-1));}assert.equal(new Set(m.assets.map(a=>a.id)).size,m.assets.length);assert.equal(new Set(i.assets.map(a=>a.id)).size,i.assets.length);});
