import initializeWamHost from '../../../third_party/wam-examples/packages/sdk/src/initializeWamHost.js';
import {PLUGIN_CATEGORIES,WamPluginRegistry,destroyPluginInstance} from '../WamPluginRegistry.js';
import '../PluginCard.js';

const $=(selector)=>document.querySelector(selector);
const context=new AudioContext({latencyHint:'interactive',sampleRate:48000});
const registry=new WamPluginRegistry();
const inputBus=context.createGain(),inputAnalyser=context.createAnalyser(),dryGain=context.createGain(),wetGain=context.createGain(),outputAnalyser=context.createAnalyser();
inputAnalyser.fftSize=256;outputAnalyser.fftSize=256;inputBus.connect(inputAnalyser);inputAnalyser.connect(dryGain);dryGain.connect(outputAnalyser);wetGain.connect(outputAnalyser);outputAnalyser.connect(context.destination);
let groupId,active=null,tuner=null,savedState=null,sourceNode=null,sourceStream=null,selectedCategory='all',liveEnabled=false;
const fileNode=context.createMediaElementSource($('#player'));
const inputSamples=new Float32Array(inputAnalyser.fftSize),outputSamples=new Float32Array(outputAnalyser.fftSize);

function log(message,error=false){const line=`${new Date().toLocaleTimeString()}  ${message}`;$('#diagnostics').textContent=`${line}\n${$('#diagnostics').textContent}`.slice(0,10000);if(error)console.error(message);}
function meter(analyser,data,element){analyser.getFloatTimeDomainData(data);let peak=0;for(const sample of data)peak=Math.max(peak,Math.abs(sample));element.value=Math.min(1,peak);}
function peak(analyser,data){analyser.getFloatTimeDomainData(data);let value=0;for(const sample of data)value=Math.max(value,Math.abs(sample));return value;}
const wait=(milliseconds)=>new Promise(resolve=>setTimeout(resolve,milliseconds));
function animate(){meter(inputAnalyser,inputSamples,$('#inputMeter'));meter(outputAnalyser,outputSamples,$('#outputMeter'));requestAnimationFrame(animate);}animate();
function updateBypass(){const bypass=$('#bypass').checked;dryGain.gain.setTargetAtTime(bypass||!active?1:0,context.currentTime,.008);wetGain.gain.setTargetAtTime(!bypass&&active?1:0,context.currentTime,.008);const button=$('#guiBypass');button.textContent=bypass?'BYPASS ON':'BYPASS OFF';button.classList.toggle('bypass-on',bypass);button.classList.toggle('bypass-off',!bypass);button.setAttribute('aria-pressed',String(bypass));}
function stopSource(){try{sourceNode?.stop?.();}catch{}try{sourceNode?.disconnect?.();}catch{}sourceNode=null;sourceStream?.getTracks().forEach(track=>track.stop());sourceStream=null;try{fileNode.disconnect();}catch{}$('#player').pause();liveEnabled=false;$('#sourceAction').classList.remove('active');}
async function enumerateInputs(){const devices=await navigator.mediaDevices.enumerateDevices();const inputs=devices.filter(device=>device.kind==='audioinput'),select=$('#inputDevice');select.replaceChildren(...inputs.map((device,index)=>new Option(device.label||`Input ${index+1}`,device.deviceId)));}
async function startSource(){await context.resume();stopSource();const mode=$('#source').value;
  if(mode==='tone'){const oscillator=context.createOscillator(),gain=context.createGain();oscillator.frequency.value=220;gain.gain.value=.025;oscillator.connect(gain).connect(inputBus);oscillator.start();sourceNode=oscillator;$('#sourceAction').textContent='Stop test tone';log('Deterministic 220 Hz test tone started.');return;}
  if(mode==='live'){if(!$('#inputDevice').options.length){const permission=await navigator.mediaDevices.getUserMedia({audio:true});permission.getTracks().forEach(track=>track.stop());await enumerateInputs();}const deviceId=$('#inputDevice').value;sourceStream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:deviceId?{exact:deviceId}:undefined,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});sourceNode=context.createMediaStreamSource(sourceStream);sourceNode.connect(inputBus);liveEnabled=true;$('#sourceAction').textContent='Disable live input';log(`Live input enabled: ${sourceStream.getAudioTracks()[0]?.label||deviceId}`);return;}
  $('#audioFile').click();
}
async function unloadActive(){if(!active)return;try{inputAnalyser.disconnect(active.plugin.audioNode);}catch{}try{active.plugin.audioNode.disconnect(wetGain);}catch{}destroyPluginInstance(active.plugin,active.gui);log(`Unloaded ${active.record.name}`);active=null;savedState=null;$('#activeName').textContent='None';$('#parameters').textContent='No parameters';for(const id of ['showGui','unload','saveState','restoreState'])$(`#${id}`).disabled=true;updateBypass();}
async function loadRecord(record,{quiet=false}={}){if(record.role==='tuner')return toggleTuner(record);await unloadActive();await context.resume();try{const plugin=await registry.instantiate(record,{groupId,audioContext:context});const inspected=await registry.inspectInstance(record,plugin);inputAnalyser.connect(plugin.audioNode);plugin.audioNode.connect(wetGain);active={record,plugin,gui:inspected.gui};$('#activeName').textContent=record.name;$('#parameters').textContent=JSON.stringify(inspected.parameters||{},null,2);for(const id of ['showGui','unload','saveState'])$(`#${id}`).disabled=false;$('#restoreState').disabled=true;updateBypass();renderCards();if(!quiet)log(`Loaded and validated ${record.name}.`);return active;}catch(error){record.diagnostics.push({stage:'runtime',level:'error',message:error.message});renderCards();log(`Cannot load ${record.name}: ${error.message}`,true);throw error;}}
async function toggleTuner(record=registry.records.find(item=>item.role==='tuner')){if(tuner){try{inputAnalyser.disconnect(tuner.plugin.audioNode);}catch{}try{tuner.silent.disconnect();}catch{}destroyPluginInstance(tuner.plugin,tuner.gui);tuner=null;$('#tunerButton').classList.remove('active');if($('#guiDialog').open)closeGui();log('Tuner closed.');return;}if(!record)return;try{const plugin=await registry.instantiate(record,{groupId,audioContext:context});const inspected=await registry.inspectInstance(record,plugin),silent=context.createGain();silent.gain.value=0;inputAnalyser.connect(plugin.audioNode);plugin.audioNode.connect(silent).connect(context.destination);tuner={record,plugin,gui:inspected.gui,silent};$('#tunerButton').classList.add('active');showGui(tuner);log('Tuner opened on a parallel input tap.');}catch(error){log(`Cannot open tuner: ${error.message}`,true);}}
function closeGui(){if($('#guiDialog').open)$('#guiDialog').close();$('#guiMount').replaceChildren();}
function showGui(target=active){if(!target?.gui)return log(`${target?.record?.name||'Plugin'} has no GUI.`,true);$('#guiTitle').textContent=target.record.name;$('#guiBypass').hidden=target.record.role==='tuner';if(!$('#guiDialog').open)$('#guiDialog').showModal();$('#guiMount').replaceChildren(target.gui);updateBypass();}
async function openRecord(record){if(record.role==='tuner'){if(tuner)showGui(tuner);else await toggleTuner(record);return;}if(active?.record===record){showGui(active);return;}const loaded=await loadRecord(record);if(loaded){$('#bypass').checked=false;updateBypass();showGui(loaded);}}
function renderCards(){const query=$('#search').value.trim().toLowerCase(),grid=$('#pluginGrid');grid.replaceChildren();const records=registry.records.filter(record=>(selectedCategory==='all'||record.category===selectedCategory)&&(!query||`${record.name} ${record.vendor} ${record.category} ${record.tags.join(' ')}`.toLowerCase().includes(query)));for(const record of records){const card=document.createElement('wam-plugin-card');card.record=record;grid.append(card);}$('#registrySummary').textContent=`${records.length} shown · ${registry.records.length} catalogued · ${registry.diagnostics.length} catalogue diagnostic(s)`;}
function renderCategories(){const nav=$('#categories'),categories=['all',...PLUGIN_CATEGORIES.filter(category=>registry.records.some(record=>record.category===category))];nav.replaceChildren(...categories.map(category=>{const button=document.createElement('button');button.textContent=category;button.classList.toggle('active',category===selectedCategory);button.onclick=()=>{selectedCategory=category;renderCategories();renderCards();};return button;}));}
async function validateAll(){const previous=active?.record,previousBypass=$('#bypass').checked,startedProbe=!sourceNode&&!sourceStream&&!$('#player').src;$('#validateAll').disabled=true;try{if(startedProbe){$('#source').value='tone';await startSource();}$('#bypass').checked=false;updateBypass();for(const record of registry.records){try{if(record.role==='tuner'){await toggleTuner(record);await wait(180);registry.markAudioValidation(record,{inputPeak:peak(inputAnalyser,inputSamples),outputPeak:peak(outputAnalyser,outputSamples)});await toggleTuner(record);renderCards();log(`PASS ${record.name}: parallel tuner branch and main-signal continuity.`);continue;}await loadRecord(record,{quiet:true});await wait(180);const levels=registry.markAudioValidation(record,{inputPeak:peak(inputAnalyser,inputSamples),outputPeak:peak(outputAnalyser,outputSamples)});renderCards();log(`PASS ${record.name}: lifecycle and audio ${levels.outputPeak.toFixed(4)} peak.`);}catch(error){record.status='audio-error';record.diagnostics.push({stage:'audio-test',level:'error',message:error.message});renderCards();log(`FAIL ${record.name}: ${error.message}`,true);}}await unloadActive();if(previous)try{await loadRecord(previous,{quiet:true});}catch{}}finally{if(startedProbe)stopSource();$('#bypass').checked=previousBypass;updateBypass();$('#validateAll').disabled=false;}}

async function initialize(){[groupId]=await initializeWamHost(context,'neuralwamp-fx-registry');await registry.load('../wamPlugins/plugins.json');renderCategories();renderCards();const tunerRecord=registry.records.find(record=>record.role==='tuner');$('#tunerButton').disabled=!tunerRecord;log(`Registry ready: ${registry.records.length} plugin(s).`);for(const diagnostic of registry.diagnostics)log(`${diagnostic.level}: ${diagnostic.message}`,diagnostic.level==='error');}
$('#pluginGrid').addEventListener('plugin-load',event=>openRecord(event.detail.record).catch(()=>{}));$('#search').oninput=renderCards;$('#bypass').onchange=updateBypass;$('#guiBypass').onclick=()=>{$('#bypass').checked=!$('#bypass').checked;updateBypass();};$('#showGui').onclick=()=>showGui();$('#unload').onclick=unloadActive;$('#saveState').onclick=async()=>{savedState=await active?.plugin.audioNode.getState?.();$('#restoreState').disabled=savedState===undefined;log('Plugin state saved.');};$('#restoreState').onclick=async()=>{await active?.plugin.audioNode.setState?.(savedState);log('Plugin state restored.');};$('#closeGui').onclick=closeGui;$('#guiDialog').addEventListener('cancel',event=>{event.preventDefault();closeGui();});$('#tunerButton').onclick=()=>tuner?showGui(tuner):toggleTuner();$('#validateAll').onclick=validateAll;
$('#source').onchange=()=>{stopSource();const mode=$('#source').value;$('#inputRow').hidden=mode!=='live';$('#audioFile').hidden=mode!=='file';$('#sourceAction').textContent=mode==='tone'?'Start test tone':mode==='live'?'Enable live input':'Choose audio file';};$('#sourceAction').onclick=async()=>{if(sourceNode||sourceStream){stopSource();$('#source').dispatchEvent(new Event('change'));log('Audio source stopped.');}else await startSource().catch(error=>log(error.message,true));};
$('#audioFile').onchange=async()=>{const file=$('#audioFile').files[0];if(!file)return;stopSource();const player=$('#player');player.src=URL.createObjectURL(file);player.hidden=false;fileNode.connect(inputBus);await context.resume();await player.play();$('#sourceAction').textContent='Stop audio file';log(`Playing ${file.name}.`);};
initialize().catch(error=>log(`Host initialization failed: ${error.message}`,true));
