import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {access} from 'node:fs/promises';

const read = (path) => readFile(new URL(`../../${path}`, import.meta.url), 'utf8');

test('Phase 4b.2 host uses a sidebar and rack without duplicating plugin controls', async () => {
  const [html, css, main] = await Promise.all([read('examples/wam/index.html'), read('examples/wam/host.css'), read('examples/wam/main.js')]);
  assert.match(html, /class="host-sidebar"/u);
  assert.match(html, /class="rack-grid"/u);
  assert.match(html, /href="\.\/host\.css"/u);
  assert.match(html, /class="embedded-player" id="playerPanel" hidden/u);
  assert.ok(html.indexOf('id="audioSource"') < html.indexOf('id="playerPanel"'));
  assert.ok(html.indexOf('id="inputDevice"') < html.indexOf('id="outputDevice"'));
  assert.ok(html.indexOf('id="inputDevice"') < html.indexOf('id="inputChannel"'));
  assert.ok(html.indexOf('id="inputChannel"') < html.indexOf('id="outputDevice"'));
  assert.doesNotMatch(html, /<section class="host-card" aria-labelledby="(?:player|output)-title"/u);
  assert.match(html, /<summary>Automated test results<\/summary>/u);
  assert.match(html, /opened with <code>\?auto=1<\/code>/u);
  assert.doesNotMatch(html, /host-(?:inputGain|outputGain|bypass)|id="cabinetMode"/u);
  assert.match(css, /grid-template-columns:\s*286px minmax\(0, 1fr\)/u);
  assert.match(css, /@media \(max-width: 720px\)/u);
  assert.match(main, /cabinet-routing-mode/u);
  assert.match(main, /node\.connect\(cabinetNode\)\.connect\(context\.destination\)/u);
  assert.match(main, /\$\('#playerPanel'\)\.hidden = !enabled/u);
  assert.match(html, /id="enableLive"[^>]*aria-pressed="false"[^>]*>Enable live input/u);
  assert.match(css, /\.live-toggle\.live-active/u);
  assert.match(main, /liveInputEnabled \? 'Disable live input' : 'Enable live input'/u);
  assert.match(main, /if \(liveInputEnabled\) \{\s*await disableLiveInput\(\)/u);
  assert.match(main, /if \(\$\('#audioSource'\)\.value !== 'live' \|\| !liveInputEnabled\) return/u);
});

test('NAM GUI is container-scoped and exposes compact top-level tabs', async () => {
  const gui = await read('src/nam-wam/gui.js');
  assert.match(gui, /const neuralWampLogoMarkup = `\s*<svg class="module-logo"/u);
  assert.match(gui, /role="img" aria-label="NeuralWAMp"/u);
  assert.match(gui, /\$\{neuralWampLogoMarkup\}/u);
  assert.match(gui, /\.module-head\s*\{[^}]*grid-template-columns:80px minmax\(0,1fr\) 80px[^}]*padding:7px 12px/u);
  assert.match(gui, /\.module-logo\s*\{[^}]*width:78px;height:25px/u);
  assert.match(gui, /\.signal-flow\s*\{[^}]*padding:4px 8px/u);
  assert.match(gui, /\.flow-stage\s*\{[^}]*padding:2px 5px[^}]*font-size:7px/u);
  await access(new URL('../../src/nam-wam/neuralwamp-logo.svg', import.meta.url));
  assert.match(gui, /class="plugin-tabs" role="tablist"/u);
  assert.match(gui, /\.plugin-tabs\s*\{[^}]*display:flex[^}]*justify-content:space-between/u);
  assert.match(gui, /\.plugin-tab\s*\{[^}]*flex:0 0 auto[^}]*padding:0 14px/u);
  assert.match(gui, /@media\(max-width:620px\)\{nam-a2-gui \.plugin-tabs\{justify-content:flex-start;overflow-x:auto\}/u);
  for (const tab of ['main','models','amp','details','preferences','about']) assert.match(gui, new RegExp(`data-plugin-tab="${tab}"`,'u'));
  assert.match(gui, /class="plugin-panel mainPanel"[^>]*data-plugin-panel="main"/u);
  assert.match(gui, /data-plugin-panel="main"><div class="signal-strip">[\s\S]*?<div class="signal-flow" role="img" aria-label="Signal path"><\/div><\/section>/u);
  assert.match(gui, /class="plugin-panel modelDrawer modelsPanel"[^>]*data-plugin-panel="models" hidden/u);
  assert.match(gui, /class="plugin-panel detailsDrawer detailsPanel"[^>]*data-plugin-panel="details" hidden/u);
  assert.match(gui, /class="plugin-panel aboutPanel"[^>]*data-plugin-panel="about" hidden/u);
  assert.match(gui, /data-plugin-tab="about">Help<\/button>/u);
  assert.match(gui, /href="https:\/\/github\.com\/micbuffa\/NAM_A2_WAM" target="_blank" rel="noopener noreferrer"/u);
  for (const heading of ['Main','Models','Amp settings','Model details','Preferences','Controls','State and storage']) assert.match(gui,new RegExp(`<h4>${heading}<\\/h4>`,'u'));
  assert.match(gui, /<article class="gettingStarted"><h4>Getting started with your guitar<\/h4><ol>/u);
  assert.match(gui, /Choose <strong>Live input<\/strong>/u);
  assert.match(gui, /Click <strong>Enable live input<\/strong>/u);
  assert.match(gui, /red <strong>Disable live input<\/strong> button to stop the microphone stream/u);
  assert.match(gui, /If your browser does not support output-device selection/u);
  assert.match(gui, /A capture selected from TONE3000 is downloaded, loaded, and kept locally/u);
  assert.match(gui, /class="modelHoverCard" role="tooltip" hidden/u);
  assert.match(gui, /setTimeout\(\(\)=>\{[^}]*element\.isConnected[^}]*element\.hidden[^}]*modelHoverInfo\(provider\(\)\)[^}]*showModelHover\(element,info\)[^}]*\},1000\)/u);
  assert.match(gui, /bindModelHover\(this\.controls\.currentToneImage/u);
  assert.match(gui, /bindModelHover\(image,\(\)=>assets\[index\]\)/u);
  for (const source of ['Factory', 'Favorites', 'External', 'TONE3000']) assert.match(gui, new RegExp(`data-source="${source}"`, 'u'));
  for (const category of ['all', 'guitar', 'bass', 'pedal']) assert.match(gui, new RegExp(`data-category="${category}"`, 'u'));
  assert.match(gui, /setFactoryCategory/u);
  assert.match(gui, /asset\.category===this\._factoryCategory/u);
  assert.match(gui, /class="tone3000Browse"/u);
  assert.match(gui, /class="tone3000Auth"/u);
  assert.match(gui, /class="tone3000Authenticate"/u);
  assert.match(gui, /class="tone3000Logo"[^>]*src="\$\{tone3000LogoUrl\}"/u);
  assert.match(gui, /showToneAuthentication\(!this\.tone3000\?\.tokens\?\.access_token\)/u);
  await access(new URL('../../src/nam-wam/tone3000/TONE3000-logo.svg', import.meta.url));
  assert.match(gui, /class="tone3000Image"/u);
  assert.match(gui, /class="currentToneImage"/u);
  assert.match(gui, /class="tone3000Image"[^>]*crossorigin="anonymous"/u);
  assert.match(gui, /class="currentToneImage"[^>]*crossorigin="anonymous"/u);
  assert.match(gui, /tone\.images/u);
  assert.match(gui, /imageUrl:\s*getToneImageUrl\(this\._tone\)/u);
  assert.match(gui, /class="tone3000DownloadedList"/u);
  assert.match(gui, /class="tone3000Clear"/u);
  assert.match(gui, /new Tone3000Downloads/u);
  assert.match(gui, /new ModelFavorites/u);
  assert.match(gui, /class="a2Variant"/u);
  assert.match(gui, /class="autoLevel"/u);
  assert.match(gui, /class="chip modelLevel inactive"/u);
  assert.match(gui, /class="calibrateLevel"/u);
  assert.match(gui, /class="useMetadataLevel"/u);
  assert.match(gui, /calibrateCurrentModelLevel/u);
  assert.match(gui, /MEASURED/u);
  assert.match(gui, /measuredLevelsStorageKey/u);
  assert.match(gui, /restoreMeasuredLevel/u);
  assert.match(gui, /Applied NAM correction:/u);
  assert.match(gui, /setAutoLevel\(autoLevel\)/u);
  assert.match(gui, /Auto level:/u);
  assert.match(gui, /setModelVariant\(preferredVariant\)/u);
  assert.match(gui, /knobMarkup\('inputGain'/u);
  assert.match(gui, /knobMarkup\('outputGain'/u);
  assert.match(gui, /input\.ondblclick=/u);
  assert.match(gui, /bindVerticalKnob\(input\)/u);
  assert.match(gui, /drag\.lastY-event\.clientY/u);
  assert.match(gui, /cursor:ns-resize/u);
  for (const id of ['noise','bass','middle','treble']) assert.match(gui, new RegExp(`knobMarkup\\('${id}'`));
  assert.doesNotMatch(gui, /<button class="eqButton"/u);
  assert.match(gui, /class="eq-panel" id="namEqPanel">/u);
  assert.match(gui, /class="eqGraph"/u);
  assert.match(gui, /class="eq-curve"/u);
  assert.match(gui, /class="eq-spectrum"/u);
  assert.match(gui, /class="eq-spectrum-input-line"/u);
  assert.match(gui, /class="eq-spectrum-filtered-line"/u);
  assert.match(gui, /class="eq-spectrum-final-line"/u);
  assert.match(gui, /<h2>NeuralWAMp<\/h2>/u);
  assert.match(gui, />by @micbuffa<\/a>/u);
  assert.match(gui, /class="signal-flow" role="img"/u);
  assert.match(gui, /renderSignalFlow\(\)/u);
  assert.match(gui, /\.\.\.\(eqPre\?\[eq\]:\[\]\)/u);
  assert.match(gui, /\.\.\.\(!eqPre\?\[eq\]:\[\]\)/u);
  assert.match(gui, /label:'Tone stack'/u);
  assert.match(gui, /stage\.enabled\?'':' off'/u);
  assert.match(gui, /class="eqBandCurves"/u);
  assert.match(gui, /class="eqNodes"/u);
  assert.match(gui, /moveEqDrag/u);
  assert.match(gui, /eqMagnitudeDb/u);
  assert.match(gui, /wheel changes Q/u);
  assert.doesNotMatch(gui, /knobMarkup\(`eq/u);
  assert.match(gui, /classList\.toggle\('is-bypassed', value >= \.5\)/u);
  assert.match(gui, /className='favoriteToggle factoryToneFavorite'/u);
  assert.match(gui, /tone3000Downloads\.save/u);
  assert.match(gui, /deleteTone3000Download/u);
  assert.match(gui, /class="factoryMaintainer"/u);
  assert.match(gui, /data-maintainer-kind="nam"/u);
  assert.match(gui, /data-maintainer-kind="ir"/u);
  assert.match(gui, /createFactoryBundle/u);
  assert.match(gui, /new URL\(window\.location\.href\)\.searchParams\.get\('maintainer'\) === '1'/u);
  assert.match(gui, /createFactoryAssetEntry/u);
  assert.match(gui, /createFactoryToneCard/u);
  assert.match(gui, /className='factoryToneViewer'/u);
  assert.match(gui, /className='factoryToneNav'/u);
  assert.match(gui, /previous\.disabled=index===0;next\.disabled=index===assets\.length-1/u);
  assert.match(gui, /previous\.onclick=\(\)=>choose\(index-1\);next\.onclick=\(\)=>choose\(index\+1\)/u);
  assert.match(gui, /className='factoryToneFilename'/u);
  assert.match(gui, /class="currentModelInfo"/u);
  assert.match(gui, /\.current-model\s*\{[^}]*grid-column:3;grid-row:1/u);
  assert.match(gui, /\.meter\[data-meter=input\]\s*\{[^}]*grid-column:1;grid-row:1/u);
  assert.match(gui, /\.meter\[data-meter=output\]\s*\{[^}]*grid-column:4;grid-row:1/u);
  assert.match(gui, /class="meter-side input-meter-side"/u);
  assert.match(gui, /class="meter-side output-meter-side"/u);
  assert.match(gui, /\.meter-side \.knob-shell\s*\{ width:28px;height:28px \}/u);
  assert.match(gui, /\.noise-side \.knob-shell\s*\{ width:28px;height:28px \}/u);
  assert.match(gui, /\.noise-side \.knob-input,nam-a2-gui \.meter-side \.knob-input\s*\{ inset:-7px auto auto -7px;width:42px;height:42px \}/u);
  assert.match(gui, /<div class="meter-side input-meter-side">[^\n]*knobMarkup\('inputGain'/u);
  assert.match(gui, /<div class="meter-side output-meter-side">[^\n]*knobMarkup\('outputGain'/u);
  assert.match(gui, /<div class="noise-side">\$\{knobMarkup\('noise','Threshold'/u);
  assert.match(gui, /class="section-switch noise-switch"><input class="noiseEnabled" type="checkbox"> Noise gate/u);
  assert.match(gui, /class="plugin-panel amp-knobs ampPanel"[^>]*data-plugin-panel="amp" hidden/u);
  assert.match(gui, /class="amp-switches"/u);
  assert.match(gui, /class="amp-controls"><section class="eq-panel"/u);
  assert.match(gui, /class="eqPosition"[\s\S]*?<\/select><\/label><\/div><section class="tone-strip"/u);
  assert.match(gui, /class="amp-switches"><label class="section-switch"><input class="toneEnabled" type="checkbox" checked> Tone<\/label><\/div>\$\{knobMarkup\('bass'/u);
  assert.match(gui, /\.tone-strip \.knob-shell\s*\{ width:28px;height:28px \}/u);
  assert.match(gui, /\.amp-controls \.tone-strip\s*\{ display:grid;grid-template-columns:repeat\(4,43px\)/u);
  assert.match(gui, /\.amp-controls \.eq-toolbar-group>label\s*\{ display:flex;align-items:center;gap:5px;min-height:32px \}/u);
  assert.match(gui, /\.amp-controls \.section-switch\s*\{ display:flex;align-items:center;justify-content:center/u);
  const ampSettings=gui.match(/<section class="plugin-panel amp-knobs ampPanel"([\s\S]*?)<section class="plugin-panel modelDrawer/u)?.[1] || '';
  for (const id of ['bass','middle','treble']) assert.match(ampSettings,new RegExp(`knobMarkup\\('${id}'`,'u'));
  assert.doesNotMatch(ampSettings,/knobMarkup\('(noise|inputGain|outputGain)'/u);
  assert.match(gui,/syncNoiseGateVisual\(\)/u);
  assert.doesNotMatch(gui,/syncToneEnabledVisual\(\)/u);
  assert.doesNotMatch(gui,/this\.controls\[id\]\.disabled=!enabled/u);
  assert.match(gui,/this\.controls\.noise\.disabled=!enabled/u);
  assert.match(ampSettings,/class="eq-panel"/u);
  assert.match(gui,/setPluginTab\(tabName/u);
  assert.match(gui,/navigatePluginTabs\(event, button\)/u);
  assert.doesNotMatch(gui,/class="noiseEnabled" type="checkbox" checked/u);
  assert.match(gui, /className='factoryToneMedia'/u);
  assert.match(gui, /className='factoryToneDetails'/u);
  assert.match(gui, /className='factoryCaptureList'/u);
  assert.match(gui, /captureButtons=assets\.map/u);
  assert.match(gui, /captureButtons\.forEach\(\(button,buttonIndex\)=>\{button\.onclick=\(\)=>choose\(buttonIndex\)/u);
  assert.match(gui, /captureList\.scrollTop=Math\.max/u);
  assert.match(gui, /\.factoryCaptureList\s*\{[^}]*overflow-y:auto/u);
  assert.match(gui, /this\.setPluginTab\('main'\)/u);
  assert.match(gui, /this\._factoryCategory='guitar'/u);
  assert.match(gui, /data-category="guitar"[^>]*aria-pressed="true"/u);
  assert.match(gui, /class="tone3000Selection factoryToneCard"/u);
  assert.match(gui, /class="tone3000Back" type="button" hidden>Back to TONE3000 main view/u);
  assert.match(gui, /this\.controls\.toneBack\.onclick = \(\) => this\.backToTone3000MainView\(\)/u);
  assert.doesNotMatch(gui, /<select class="tone3000Model"/u);
  assert.match(gui, /class="factoryToneNav tone3000CapturePrevious"/u);
  assert.match(gui, /class="factoryToneNav tone3000CaptureNext"/u);
  assert.match(gui, /class="factoryCaptureList tone3000CaptureList"/u);
  assert.match(gui, /this\.controls\.toneCapturePrevious\.onclick = \(\) => this\.loadTone3000Model\(this\._toneModelIndex-1\)/u);
  assert.match(gui, /this\.controls\.toneCaptureNext\.onclick = \(\) => this\.loadTone3000Model\(this\._toneModelIndex\+1\)/u);
  assert.match(gui, /button\.onclick=\(\)=>this\.loadTone3000Model\(index\)/u);
  assert.match(gui, /const captureCountLabel = \(count\) =>/u);
  assert.match(gui, /captureLabel\.textContent=captureCountLabel\(assets\.length\)/u);
  assert.match(gui, /this\.controls\.toneCaptureLabel\.textContent = captureCountLabel\(this\._toneModels\.length\)/u);
  assert.match(gui, /media\.append\(title,meta,viewer,filename,footer\);details\.append\(captureLabel,captureList\)/u);
  assert.match(gui, /this\.updateOutputGlow\(peakDb,rmsDb\)/u);
  assert.match(gui, /strip\.style\.boxShadow=/u);
  assert.match(gui, /syncEqEnabledVisual\(\)/u);
  assert.match(gui, /EQ BYPASSED/u);
  assert.doesNotMatch(gui, /tone3000Load|toneLoad/u);
  assert.match(gui, /filename\.textContent=asset\.filename/u);
  assert.match(gui, /factoryProvenance/u);
  assert.match(gui, /File: \$\{asset\.filename\}/u);
  assert.match(gui, /gear:\s*this\._tone\?\.gear \|\| this\._tone\?\.gear_type/u);
  assert.match(gui, /\.tone3000Image\s*\{[^}]*object-fit:contain/u);
  assert.match(gui, /\.currentToneImage\s*\{[^}]*object-fit:contain/u);
  assert.match(gui, /completeAuthorization\(location\)/u);
  assert.match(gui, /this\.setPluginTab\('models'\)/u);
  assert.match(gui, /loadTone3000Selection\(result\.toneId, \{autoLoad: true\}\)/u);
  assert.match(gui, /window\.open\('about:blank', 'tone3000-oauth'/u);
  assert.doesNotMatch(gui, /window\.location\.assign\(await this\.tone3000/u);
  assert.match(gui, /tone3000Catalog/u);
  assert.match(gui, /data-tone-feed="trending"/u);
  assert.match(gui, /listTrendingTones/u);
  assert.match(gui, /authenticateTone3000/u);
  assert.doesNotMatch(gui, /100vw|position:\s*fixed|(?:^|[}\s,])body\s*\{/mu);
});

test('Cabinet GUI belongs to the NeuralWAMp family and manages rich IR sources', async () => {
  const gui = await read('src/cabinet-wam/gui.js');
  assert.match(gui, /class="routingMode"/u);
  assert.match(gui, /<option value="auto">AUTO<\/option>/u);
  assert.match(gui, /<h2>NeuralWAMp Cabinet<\/h2>/u);
  assert.match(gui, /const cabinetLogoMarkup=/u);
  for (const tab of ['main','irs','details','help']) assert.match(gui,new RegExp(`data-tab="${tab}"`,'u'));
  for (const source of ['Factory','Favorites','External','TONE3000']) assert.match(gui,new RegExp(`data-source="${source}"`,'u'));
  for (const category of ['all','speaker','space','outboard','experimental','other']) assert.match(gui,new RegExp(`data-category="${category}"`,'u'));
  assert.match(gui, /DEFAULT_IR_PATH='tone3000\/outmodedelectronics\/Celestion Vintage 30 - 2002 Mesa Boogie 4x12 - SM57--t45023\/captures\/V30 LL 4FB 4x12 SM57 0\.50in 0--m239290\.wav'/u);
  assert.match(gui, /class="chip irActivity"/u);
  assert.match(gui, /\.current-ir\.is-active/u);
  assert.match(gui, /\.current-ir\.is-bypassed/u);
  assert.match(gui, /\.routingStatus\.is-active/u);
  assert.match(gui, /\.routingStatus\.is-bypassed/u);
  assert.match(gui, /\.cab-module\.is-bypassed/u);
  assert.match(gui, /querySelector\('\.cab-module'\)\.classList\.toggle\('is-bypassed',bypassed\)/u);
  assert.match(gui, /createToneCard/u);
  assert.match(gui, /format:'ir'/u);
  assert.match(gui, /searchTones/u);
  assert.match(gui, /new ImpulseResponseLibrary/u);
  assert.match(gui, /createFactoryBundle/u);
  assert.match(gui, /class="maintainer" hidden/u);
  assert.match(gui, /\.maintainer\{order:-2/u);
  assert.ok(gui.indexOf('<section class="tone3000-panel"') < gui.indexOf('<div class="browser-tools"'));
  assert.match(gui, /Download selected Factory IR bundle \(\.zip\)/u);
  assert.match(gui, /nam-cabinet-gui \[hidden\]\{display:none!important\}/u);
  await access(new URL('../../src/cabinet-wam/neuralwamp-cabinet-logo.svg', import.meta.url));
  await access(new URL('../../src/cabinet-wam/IRs/tone3000/outmodedelectronics/Celestion Vintage 30 - 2002 Mesa Boogie 4x12 - SM57--t45023/captures/V30 LL 4FB 4x12 SM57 0.50in 0--m239290.wav', import.meta.url));
  assert.doesNotMatch(gui, /100vw|position:\s*fixed|(?:^|[}\s,])body\s*\{/mu);
});

test('asset accordions keep the selected model path open and highlighted', async () => {
  const browser = await read('src/shared/assetBrowser.js');
  assert.match(browser, /details\.open=!!query\|\|containsSelected\(branch\)/u);
  assert.match(browser, /asset\.id===selectedId\)button\.classList\.add\('selected'\)/u);
  assert.match(browser, /renderGroup\?\.\(\{name:key,assets:branch\.__assets,selectedId,onSelect,isFavorite,toggleFavorite,favoriteButton\}\)/u);
});

test('NAM GUI loads the first Bogner guitar capture only when no model was restored', async () => {
  const gui = await read('src/nam-wam/gui.js');
  const manifest = JSON.parse(await read('src/nam-wam/models-manifest.json'));
  const firstCapture = manifest.assets.find((asset) => asset.category === 'guitar' && Number(asset.provenance?.toneId) === 80705);
  assert.equal(firstCapture?.filename, '[AMP] UBER--m689732.nam');
  assert.match(gui, /const defaultFactoryToneId = 80705/u);
  assert.match(gui, /if\(state\.model\?\.data\)\{await this\._modelListener\(null,state\.model\);return;\}/u);
  assert.match(gui, /this\._assets\.find\(\(asset\)=>asset\.category==='guitar'&&Number\(asset\.provenance\?\.toneId\)===defaultFactoryToneId\)/u);
  assert.match(gui, /await this\.node\.loadModelText\(text,firstCapture\.filename,factoryProvenance\(firstCapture\)\)/u);
});
