import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {access} from 'node:fs/promises';

const read = (path) => readFile(new URL(`../../${path}`, import.meta.url), 'utf8');

test('Phase 4b.2 host uses a sidebar and rack without duplicating plugin controls', async () => {
  const [html, css, main] = await Promise.all([read('examples/wam/index.html'), read('examples/wam/host.css'), read('examples/wam/main.js')]);
  assert.match(html, /class="host-sidebar"/u);
  assert.match(html, /class="rack-grid"/u);
  assert.match(html, /href="\.\/host\.css"/u);
  assert.doesNotMatch(html, /host-(?:inputGain|outputGain|bypass)|id="cabinetMode"/u);
  assert.match(css, /grid-template-columns:\s*286px minmax\(0, 1fr\)/u);
  assert.match(css, /@media \(max-width: 720px\)/u);
  assert.match(main, /cabinet-routing-mode/u);
  assert.match(main, /node\.connect\(cabinetNode\)\.connect\(context\.destination\)/u);
});

test('NAM GUI is container-scoped and keeps compact source/details drawers', async () => {
  const gui = await read('src/nam-wam/gui.js');
  assert.match(gui, /const neuralWampLogoMarkup = `\s*<svg class="module-logo"/u);
  assert.match(gui, /role="img" aria-label="NeuralWAMp"/u);
  assert.match(gui, /\$\{neuralWampLogoMarkup\}/u);
  await access(new URL('../../src/nam-wam/neuralwamp-logo.svg', import.meta.url));
  assert.match(gui, /class="drawer modelDrawer"/u);
  assert.match(gui, /class="drawer detailsDrawer"/u);
  for (const source of ['Factory', 'Favorites', 'External', 'TONE3000']) assert.match(gui, new RegExp(`data-source="${source}"`, 'u'));
  for (const category of ['all', 'guitar', 'bass', 'pedal']) assert.match(gui, new RegExp(`data-category="${category}"`, 'u'));
  assert.match(gui, /setFactoryCategory/u);
  assert.match(gui, /asset\.category===this\._factoryCategory/u);
  assert.match(gui, /class="tone3000Browse"/u);
  assert.match(gui, /class="tone3000Auth"/u);
  assert.match(gui, /class="tone3000Authenticate"/u);
  assert.match(gui, /class="tone3000Logo"[^>]*src="\$\{tone3000LogoUrl\}"/u);
  assert.match(gui, /showToneAuthentication\(!this\.tone3000\?\.tokens\?\.access_token\)/u);
  await access(new URL('../../src/nam-wam/tone3000/TONE3000-logo.svg', import.meta.url));
  assert.match(gui, /class="tone3000Image"/u);
  assert.match(gui, /class="currentToneImage"/u);
  assert.match(gui, /class="tone3000Image"[^>]*crossorigin="anonymous"/u);
  assert.match(gui, /class="currentToneImage"[^>]*crossorigin="anonymous"/u);
  assert.match(gui, /tone\.images/u);
  assert.match(gui, /imageUrl:\s*getToneImageUrl\(this\._tone\)/u);
  assert.match(gui, /class="tone3000DownloadedList"/u);
  assert.match(gui, /class="tone3000Clear"/u);
  assert.match(gui, /new Tone3000Downloads/u);
  assert.match(gui, /new ModelFavorites/u);
  assert.match(gui, /class="a2Variant"/u);
  assert.match(gui, /class="autoLevel"/u);
  assert.match(gui, /class="chip modelLevel inactive"/u);
  assert.match(gui, /class="calibrateLevel"/u);
  assert.match(gui, /class="useMetadataLevel"/u);
  assert.match(gui, /calibrateCurrentModelLevel/u);
  assert.match(gui, /MEASURED/u);
  assert.match(gui, /measuredLevelsStorageKey/u);
  assert.match(gui, /restoreMeasuredLevel/u);
  assert.match(gui, /Applied NAM correction:/u);
  assert.match(gui, /setAutoLevel\(autoLevel\)/u);
  assert.match(gui, /Auto level:/u);
  assert.match(gui, /setModelVariant\(preferredVariant\)/u);
  assert.match(gui, /knobMarkup\('inputGain'/u);
  assert.match(gui, /knobMarkup\('outputGain'/u);
  assert.match(gui, /input\.ondblclick=/u);
  assert.match(gui, /bindVerticalKnob\(input\)/u);
  assert.match(gui, /drag\.lastY-event\.clientY/u);
  assert.match(gui, /cursor:ns-resize/u);
  for (const id of ['noise','bass','middle','treble']) assert.match(gui, new RegExp(`knobMarkup\\('${id}'`));
  assert.match(gui, /class="eqButton"/u);
  assert.match(gui, /class="eq-panel"[^>]*hidden/u);
  assert.match(gui, /class="eqGraph"/u);
  assert.match(gui, /class="eq-curve"/u);
  assert.match(gui, /class="eq-spectrum"/u);
  assert.match(gui, /class="eq-spectrum-input-line"/u);
  assert.match(gui, /class="eq-spectrum-filtered-line"/u);
  assert.match(gui, /class="eq-spectrum-final-line"/u);
  assert.match(gui, /<h2>NeuralWAMp<\/h2>/u);
  assert.match(gui, />by @micbuffa<\/a>/u);
  assert.match(gui, /class="signal-flow" role="img"/u);
  assert.match(gui, /renderSignalFlow\(\)/u);
  assert.match(gui, /\.\.\.\(eqPre\?\[eq\]:\[\]\)/u);
  assert.match(gui, /\.\.\.\(!eqPre\?\[eq\]:\[\]\)/u);
  assert.match(gui, /label:'Tone stack'/u);
  assert.match(gui, /stage\.enabled\?'':' off'/u);
  assert.match(gui, /class="eqBandCurves"/u);
  assert.match(gui, /class="eqNodes"/u);
  assert.match(gui, /moveEqDrag/u);
  assert.match(gui, /eqMagnitudeDb/u);
  assert.match(gui, /wheel changes Q/u);
  assert.doesNotMatch(gui, /knobMarkup\(`eq/u);
  assert.match(gui, /classList\.toggle\('is-bypassed', value >= \.5\)/u);
  assert.match(gui, /className='favoriteToggle'/u);
  assert.match(gui, /tone3000Downloads\.save/u);
  assert.match(gui, /deleteTone3000Download/u);
  assert.match(gui, /class="factoryMaintainer"/u);
  assert.match(gui, /data-maintainer-kind="nam"/u);
  assert.match(gui, /data-maintainer-kind="ir"/u);
  assert.match(gui, /createFactoryBundle/u);
  assert.match(gui, /new URL\(window\.location\.href\)\.searchParams\.get\('maintainer'\) === '1'/u);
  assert.match(gui, /createFactoryAssetEntry/u);
  assert.match(gui, /createFactoryToneCard/u);
  assert.match(gui, /className='factoryCaptureList'/u);
  assert.match(gui, /button\.textContent=asset\.filename/u);
  assert.match(gui, /factoryProvenance/u);
  assert.match(gui, /File: \$\{asset\.filename\}/u);
  assert.match(gui, /gear:\s*this\._tone\?\.gear \|\| this\._tone\?\.gear_type/u);
  assert.match(gui, /\.tone3000Image\s*\{[^}]*object-fit:contain/u);
  assert.match(gui, /\.currentToneImage\s*\{[^}]*object-fit:contain/u);
  assert.match(gui, /completeAuthorization\(location\)/u);
  assert.match(gui, /this\.controls\.modelDrawer\.open = true/u);
  assert.match(gui, /loadTone3000Selection\(result\.toneId, \{autoLoad: true\}\)/u);
  assert.match(gui, /window\.open\('about:blank', 'tone3000-oauth'/u);
  assert.doesNotMatch(gui, /window\.location\.assign\(await this\.tone3000/u);
  assert.match(gui, /tone3000Catalog/u);
  assert.match(gui, /data-tone-feed="trending"/u);
  assert.match(gui, /listTrendingTones/u);
  assert.match(gui, /authenticateTone3000/u);
  assert.doesNotMatch(gui, /100vw|position:\s*fixed|(?:^|[}\s,])body\s*\{/mu);
});

test('Cabinet GUI is container-scoped and exposes AUTO plus collapsible IR sources', async () => {
  const gui = await read('src/cabinet-wam/gui.js');
  assert.match(gui, /class="routingMode"/u);
  assert.match(gui, /<option value="auto">AUTO<\/option>/u);
  assert.match(gui, /class="drawer irDrawer"/u);
  assert.match(gui, /data-source="Factory"/u);
  assert.match(gui, /data-source="External"/u);
  assert.match(gui, /DEFAULT_IR_PATH = 'Celestion V30\/v30 m160\.wav'/u);
  assert.match(gui, /class="chip irActivity"/u);
  assert.match(gui, /\.current-ir\.is-active/u);
  assert.match(gui, /\.current-ir\.is-bypassed/u);
  assert.match(gui, /\.routingStatus\.is-active/u);
  assert.match(gui, /\.routingStatus\.is-bypassed/u);
  assert.match(gui, /\.cab-module\.is-bypassed/u);
  assert.match(gui, /querySelector\('\.cab-module'\)\.classList\.toggle\('is-bypassed',bypassed\)/u);
  assert.match(gui, /createFactoryToneCard/u);
  await access(new URL('../../src/cabinet-wam/IRs/Celestion V30/v30 m160.wav', import.meta.url));
  assert.doesNotMatch(gui, /100vw|position:\s*fixed|(?:^|[}\s,])body\s*\{/mu);
});

test('asset accordions keep the selected model path open and highlighted', async () => {
  const browser = await read('src/shared/assetBrowser.js');
  assert.match(browser, /details\.open=!!query\|\|containsSelected\(branch\)/u);
  assert.match(browser, /asset\.id===selectedId\)button\.classList\.add\('selected'\)/u);
  assert.match(browser, /renderGroup\?\.\(\{name:key,assets:branch\.__assets,selectedId,onSelect,isFavorite,toggleFavorite,favoriteButton\}\)/u);
});
