
/*
Code generated with Faust version 2.28.8
Compilation options: -lang wasm-ib -scal -ftz 2
*/

function getJSONDeadGateWithParams() {
	return '{"name": "DeadGateWithParams","filename": "DeadGateWithParams.dsp","version": "2.28.8","compile_options": "-lang wasm-ib -scal -ftz 2","include_pathnames": ["/usr/local/share/faust","/usr/local/share/faust","/usr/share/faust",".","/tmp/sessions/62CA649144CEE5061B77AD316005D139E12C1F3D/web/wap"],"size": 1188,"inputs": 2,"outputs": 2,"meta": [ { "analyzers_lib_name": "Faust Analyzer Library" },{ "analyzers_lib_version": "0.1" },{ "author": "Oleg Kapitonov" },{ "basics_lib_name": "Faust Basic Element Library" },{ "basics_lib_version": "0.1" },{ "compilation_options": "-single -scal -I libraries/ -I project/ -lang wasm" },{ "filename": "DeadGateWithParams.dsp" },{ "filters_lib_filterbank_author": "Julius O. Smith III" },{ "filters_lib_filterbank_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_filterbank_license": "MIT-style STK-4.3 license" },{ "filters_lib_fir_author": "Julius O. Smith III" },{ "filters_lib_fir_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_fir_license": "MIT-style STK-4.3 license" },{ "filters_lib_highpass_author": "Julius O. Smith III" },{ "filters_lib_highpass_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_highpass_plus_lowpass_author": "Julius O. Smith III" },{ "filters_lib_highpass_plus_lowpass_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_highpass_plus_lowpass_license": "MIT-style STK-4.3 license" },{ "filters_lib_iir_author": "Julius O. Smith III" },{ "filters_lib_iir_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_iir_license": "MIT-style STK-4.3 license" },{ "filters_lib_lowpass0_highpass1": "MIT-style STK-4.3 license" },{ "filters_lib_lowpass0_highpass1_author": "Julius O. Smith III" },{ "filters_lib_lowpass_author": "Julius O. Smith III" },{ "filters_lib_lowpass_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_lowpass_license": "MIT-style STK-4.3 license" },{ "filters_lib_name": "Faust Filters Library" },{ "filters_lib_tf1_author": "Julius O. Smith III" },{ "filters_lib_tf1_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_tf1_license": "MIT-style STK-4.3 license" },{ "filters_lib_tf1s_author": "Julius O. Smith III" },{ "filters_lib_tf1s_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_tf1s_license": "MIT-style STK-4.3 license" },{ "filters_lib_tf2_author": "Julius O. Smith III" },{ "filters_lib_tf2_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_tf2_license": "MIT-style STK-4.3 license" },{ "filters_lib_tf2s_author": "Julius O. Smith III" },{ "filters_lib_tf2s_copyright": "Copyright (C) 2003-2019 by Julius O. Smith III <jos@ccrma.stanford.edu>" },{ "filters_lib_tf2s_license": "MIT-style STK-4.3 license" },{ "library_path": "FaustDSP" },{ "license": "GPLv3" },{ "maths_lib_author": "GRAME" },{ "maths_lib_copyright": "GRAME" },{ "maths_lib_license": "LGPL with exception" },{ "maths_lib_name": "Faust Math Library" },{ "maths_lib_version": "2.3" },{ "misceffects_lib_name": "Misc Effects Library" },{ "misceffects_lib_version": "2.0" },{ "name": "DeadGateWithParams" },{ "platform_lib_name": "Generic Platform Library" },{ "platform_lib_version": "0.1" },{ "signals_lib_name": "Faust Signal Routing Library" },{ "signals_lib_version": "0.0" },{ "version": "0.1b" }],"ui": [ {"type": "vgroup","label": "DeadGateWithParams","items": [ {"type": "vslider","label": "Attack","address": "/DeadGateWithParams/Attack","index": 0,"meta": [{ "style": "knob" },{ "unit": "s" }],"init": 0.01,"min": 0,"max": 0.04,"step": 0.001},{"type": "vslider","label": "Dead Zone","address": "/DeadGateWithParams/Dead_Zone","index": 48,"meta": [{ "style": "knob" }],"init": -120,"min": -120,"max": 0,"step": 0.001},{"type": "vslider","label": "Hold","address": "/DeadGateWithParams/Hold","index": 400,"meta": [{ "style": "knob" },{ "unit": "s" }],"init": 0.1,"min": 0,"max": 0.3,"step": 0.01},{"type": "vslider","label": "Noise Gate","address": "/DeadGateWithParams/Noise_Gate","index": 388,"meta": [{ "style": "knob" }],"init": -120,"min": -120,"max": 0,"step": 0.001},{"type": "vslider","label": "Release","address": "/DeadGateWithParams/Release","index": 4,"meta": [{ "style": "knob" },{ "unit": "s" }],"init": 0.02,"min": 0,"max": 0.04,"step": 0.001}]}]}';
}
function getBase64CodeDeadGateWithParams() { return "AGFzbQEAAAAB24CAgAARYAJ/fwBgBH9/f38AYAF9AX1gAX8Bf2ABfwF/YAJ/fwF9YAF/AX9gAn9/AGABfwBgAn9/AGACf38AYAF/AGACf38Bf2ACf38Bf2ACfX0BfWADf399AGABfQF9AqWAgIAAAwNlbnYFX2V4cGYAAgNlbnYFX3Bvd2YADgNlbnYFX3RhbmYAEAOPgICAAA4AAQMEBQYHCAkKCwwNDwWMgICAAAEBhICAgADsh4CAAAe6gYCAAAwHY29tcHV0ZQAEDGdldE51bUlucHV0cwAFDWdldE51bU91dHB1dHMABg1nZXRQYXJhbVZhbHVlAAcNZ2V0U2FtcGxlUmF0ZQAIBGluaXQACQ1pbnN0YW5jZUNsZWFyAAoRaW5zdGFuY2VDb25zdGFudHMACwxpbnN0YW5jZUluaXQADBppbnN0YW5jZVJlc2V0VXNlckludGVyZmFjZQANDXNldFBhcmFtVmFsdWUAEAZtZW1vcnkCAAr79ICAAA6CgICAAAALjcKAgAACHn+BAX1BACEEQQAhBUEAIQZBACEHQwAAAAAhIkMAAAAAISNDAAAAACEkQQAhCEMAAAAAISVDAAAAACEmQwAAAAAhJ0MAAAAAIShDAAAAACEpQQAhCUEAIQpDAAAAACEqQQAhC0MAAAAAIStBACEMQwAAAAAhLEMAAAAAIS1DAAAAACEuQwAAAAAhL0MAAAAAITBDAAAAACExQwAAAAAhMkMAAAAAITNDAAAAACE0QwAAAAAhNUMAAAAAITZDAAAAACE3QwAAAAAhOEMAAAAAITlDAAAAACE6QwAAAAAhO0MAAAAAITxDAAAAACE9QwAAAAAhPkEAIQ1BACEOQQAhD0MAAAAAIT9DAAAAACFAQwAAAAAhQUMAAAAAIUJDAAAAACFDQwAAAAAhREMAAAAAIUVDAAAAACFGQwAAAAAhR0MAAAAAIUhDAAAAACFJQwAAAAAhSkMAAAAAIUtDAAAAACFMQwAAAAAhTUMAAAAAIU5DAAAAACFPQwAAAAAhUEMAAAAAIVFDAAAAACFSQwAAAAAhU0EAIRBBACERQQAhEkMAAAAAIVRDAAAAACFVQwAAAAAhVkMAAAAAIVdDAAAAACFYQwAAAAAhWUMAAAAAIVpDAAAAACFbQwAAAAAhXEMAAAAAIV1DAAAAACFeQwAAAAAhX0MAAAAAIWBDAAAAACFhQwAAAAAhYkMAAAAAIWNDAAAAACFkQwAAAAAhZUMAAAAAIWZBACETQQAhFEEAIRVDAAAAACFnQwAAAAAhaEMAAAAAIWlDAAAAACFqQwAAAAAha0MAAAAAIWxDAAAAACFtQwAAAAAhbkMAAAAAIW9DAAAAACFwQwAAAAAhcUMAAAAAIXJDAAAAACFzQwAAAAAhdEMAAAAAIXVDAAAAACF2QwAAAAAhd0EAIRZBACEXQQAhGEMAAAAAIXhDAAAAACF5QwAAAAAhekMAAAAAIXtDAAAAACF8QwAAAAAhfUMAAAAAIX5DAAAAACF/QwAAAAAhgAFDAAAAACGBAUMAAAAAIYIBQwAAAAAhgwFDAAAAACGEAUMAAAAAIYUBQwAAAAAhhgFBACEZQQAhGkEAIRtDAAAAACGHAUMAAAAAIYgBQwAAAAAhiQFDAAAAACGKAUMAAAAAIYsBQwAAAAAhjAFDAAAAACGNAUMAAAAAIY4BQwAAAAAhjwFDAAAAACGQAUMAAAAAIZEBQwAAAAAhkgFDAAAAACGTAUEAIRxBACEdQQAhHkMAAAAAIZQBQwAAAAAhlQFDAAAAACGWAUMAAAAAIZcBQwAAAAAhmAFDAAAAACGZAUMAAAAAIZoBQwAAAAAhmwFDAAAAACGcAUMAAAAAIZ0BQQAhH0EAISBBACEhQwAAAAAhngFDAAAAACGfAUMAAAAAIaABQwAAAAAhoQFDAAAAACGiASACQQBqKAIAIQQgAkEEaigCACEFIANBAGooAgAhBiADQQRqKAIAIQdBACoCACEiQQAqAgQhIyAiICOWISQgJItDAAAANF0hCCAIBH1DAAAAAAVDAAAAAEEAKgIQIAgEfUMAAIA/BSAkC5WTEAALISVDAAAgQUPNzEw9QQAqAjCUEAEhJkMAAIC/ICaUISdDAACAPyAlkyEoQwAAIEFDzcxMPUEAKgKEA5QQASEpQQAqAgxBACoCkAOUqCEJICKLQwAAADRdIQogCgR9QwAAAAAFQwAAAABBACoCECAKBH1DAACAPwUgIguVkxAACyEqICOLQwAAADRdIQsgCwR9QwAAAAAFQwAAAABBACoCECALBH1DAACAPwUgIwuVkxAACyErQQAhDANAAkAgBCAMaioCACAFIAxqKgIAkiEsQQAgLDgCREEAKgJAQQAqAkiUQQAqAkxBACoCUEEAKgJYlEEAKgI4ICyUk5STIS1BACAtvEGAgID8B3EEfSAtBUMAAAAACzgCVCAmQQAqAlSXICdBACoCVJaSIS5BACAuOAJcQQAqAixBACoCYJRBACoCZEEAKgJoQQAqAnCUQQAqAhggLpSTlJMhL0EAIC+8QYCAgPwHcQR9IC8FQwAAAAALOAJsQQAqAmxBACoCHEEAKgJ0QQAqAoQBlEEAKgJ4QQAqAoABlJKUkyEwQQAgMLxBgICA/AdxBH0gMAVDAAAAAAs4AnxBACoCrAFBACoCtAGUITFBACoCHEEAKgIkQQAqAnyUQQAqAogBQQAqAoABlJJBACoCJEEAKgKEAZSSlEEAKgKYAUEAKgKgAUEAKgK4AZQgMZKUkyEyQQAgMrxBgICA/AdxBH0gMgVDAAAAAAs4ArABQQAqAtwBQQAqAuQBlCEzQQAqArgBQQAqApgBIDFBACoCoAFBACoCsAGUkpSSQQAqAsgBQQAqAtABQQAqAugBlCAzkpSTITRBACA0vEGAgID8B3EEfSA0BUMAAAAACzgC4AFBACoCjAJBACoClAKUITVBACoC6AFBACoCyAEgM0EAKgLQAUEAKgLgAZSSlJJBACoC+AFBACoCgAJBACoCmAKUIDWSlJMhNkEAIDa8QYCAgPwHcQR9IDYFQwAAAAALOAKQAkEAKgK8AkEAKgLEApQhN0EAKgKYAkEAKgL4ASA1QQAqAoACQQAqApAClJKUkkEAKgKoAkEAKgKwAkEAKgLIApQgN5KUkyE4QQAgOLxBgICA/AdxBH0gOAVDAAAAAAs4AsACQQAqAuwCQQAqAvQClCE5QQAqAsgCQQAqAqgCIDdBACoCsAJBACoCwAKUkpSSQQAqAtgCQQAqAuACQQAqAvgClCA5kpSTITpBACA6vEGAgID8B3EEfSA6BUMAAAAACzgC8AJBACoC+AJBACoC2AIgOUEAKgLgAkEAKgLwApSSlJIhO0EAKgKAAyAllCA7iyAolJIhPEEAIDy8QYCAgPwHcQR9IDwFQwAAAAALOAL8AkEAKgL8AiE9ID28QYCAgPwHcQR9ID0FQwAAAAALIT4gPiApXiENQQAgDTYCiAMgCSANQQAoAowDSGwhDkEAKAKYA0F/aiEPQQAgDiAPSAR/IA8FIA4LNgKUAyANskEAKAKUA0EASrKXiyE/QQAqAqgDID9eBH0gKwUgKgshQEEAKgKgAyBAlCA/QwAAgD8gQJOUkiFBQQAgQbxBgICA/AdxBH0gQQVDAAAAAAs4ApwDQQAqApwDIUJBACBCvEGAgID8B3EEfSBCBUMAAAAACzgCpANDAAAAAEEAKgJkQQAqAmhBACoCuAOUIC5BACoCYJKTlJMhQ0EAIEO8QYCAgPwHcQR9IEMFQwAAAAALOAK0A0EAKgK0A0EAKgIcQQAqAnRBACoCxAOUQQAqAnhBACoCwAOUkpSTIURBACBEvEGAgID8B3EEfSBEBUMAAAAACzgCvANBACoCxANBACoCvANDAAAAQEEAKgLAA5SSkiFFQQAgRTgCyANBACoCHEEAKgKwAyBFlEEAKgLQA0EAKgLMA5SSlEEAKgLUA0EAKgLcA5STIUZBACBGvEGAgID8B3EEfSBGBUMAAAAACzgC2ANBACoC2ANBACoCrANBACoC4ANBACoC7AOUQQAqAqwBQQAqAugDlJKUkyFHQQAgR7xBgICA/AdxBH0gRwVDAAAAAAs4AuQDQQAqAtwBQQAqAvgDlCFIQQAqAqwDQQAqAqgBQQAqAuQDlEEAKgLwA0EAKgLoA5SSQQAqAqgBQQAqAuwDlJKUQQAqAsgBQQAqAtABQQAqAvwDlCBIkpSTIUlBACBJvEGAgID8B3EEfSBJBUMAAAAACzgC9ANBACoCjAJBACoChASUIUpBACoC/ANBACoCyAEgSEEAKgLQAUEAKgL0A5SSlJJBACoC+AFBACoCgAJBACoCiASUIEqSlJMhS0EAIEu8QYCAgPwHcQR9IEsFQwAAAAALOAKABEEAKgK8AkEAKgKQBJQhTEEAKgKIBEEAKgL4ASBKQQAqAoACQQAqAoAElJKUkkEAKgKoAkEAKgKwAkEAKgKUBJQgTJKUkyFNQQAgTbxBgICA/AdxBH0gTQVDAAAAAAs4AowEQQAqAuwCQQAqApwElCFOQQAqApQEQQAqAqgCIExBACoCsAJBACoCjASUkpSSQQAqAtgCQQAqAuACQQAqAqAElCBOkpSTIU9BACBPvEGAgID8B3EEfSBPBUMAAAAACzgCmARBACoCoARBACoC2AIgTkEAKgLgAkEAKgKYBJSSlJIhUCAlQQAqAqgElCAoIFCLlJIhUUEAIFG8QYCAgPwHcQR9IFEFQwAAAAALOAKkBEEAKgKkBCFSIFK8QYCAgPwHcQR9IFIFQwAAAAALIVMgUyApXiEQQQAgEDYCrAQgCSAQQQAoArAESGwhEUEAKAK4BEF/aiESQQAgESASSAR/IBIFIBELNgK0BCAQskEAKAK0BEEASrKXiyFUQQAqAsgEIFReBH0gKwUgKgshVUEAKgLABCBVlCBUQwAAgD8gVZOUkiFWQQAgVrxBgICA/AdxBH0gVgVDAAAAAAs4ArwEQQAqArwEIVdBACBXvEGAgID8B3EEfSBXBUMAAAAACzgCxARDAAAAAEEAKgLUBEEAKgKcAUEAKgLcBJRBACoCHCBFQQAqAswDkpSTlJMhWEEAIFi8QYCAgPwHcQR9IFgFQwAAAAALOALYBEEAKgLYBEEAKgKsA0EAKgLgA0EAKgLoBJRBACoCrAFBACoC5ASUkpSTIVlBACBZvEGAgID8B3EEfSBZBUMAAAAACzgC4ARBACoC6ARBACoC4ARDAAAAQEEAKgLkBJSSkiFaQQAgWjgC7ARBACoCrANBACoC0AQgWpRBACoC9ARBACoC8ASUkpRBACoC+ARBACoCgAWUkyFbQQAgW7xBgICA/AdxBH0gWwVDAAAAAAs4AvwEQQAqAvwEQQAqAswEQQAqAoQFQQAqApAFlEEAKgLcAUEAKgKMBZSSlJMhXEEAIFy8QYCAgPwHcQR9IFwFQwAAAAALOAKIBUEAKgKMAkEAKgKcBZQhXUEAKgLMBEEAKgLYAUEAKgKIBZRBACoClAVBACoCjAWUkkEAKgLYAUEAKgKQBZSSlEEAKgL4AUEAKgKAAkEAKgKgBZQgXZKUkyFeQQAgXrxBgICA/AdxBH0gXgVDAAAAAAs4ApgFQQAqArwCQQAqAqgFlCFfQQAqAqAFQQAqAvgBIF1BACoCgAJBACoCmAWUkpSSQQAqAqgCQQAqArACQQAqAqwFlCBfkpSTIWBBACBgvEGAgID8B3EEfSBgBUMAAAAACzgCpAVBACoC7AJBACoCtAWUIWFBACoCrAVBACoCqAIgX0EAKgKwAkEAKgKkBZSSlJJBACoC2AJBACoC4AJBACoCuAWUIGGSlJMhYkEAIGK8QYCAgPwHcQR9IGIFQwAAAAALOAKwBUEAKgK4BUEAKgLYAiBhQQAqAuACQQAqArAFlJKUkiFjICVBACoCwAWUICggY4uUkiFkQQAgZLxBgICA/AdxBH0gZAVDAAAAAAs4ArwFQQAqArwFIWUgZbxBgICA/AdxBH0gZQVDAAAAAAshZiBmICleIRNBACATNgLEBSAJIBNBACgCyAVIbCEUQQAoAtAFQX9qIRVBACAUIBVIBH8gFQUgFAs2AswFIBOyQQAoAswFQQBKspeLIWdBACoC4AUgZ14EfSArBSAqCyFoQQAqAtgFIGiUIGdDAACAPyBok5SSIWlBACBpvEGAgID8B3EEfSBpBUMAAAAACzgC1AVBACoC1AUhakEAIGq8QYCAgPwHcQR9IGoFQwAAAAALOALcBUMAAAAAQQAqAuwFQQAqAswBQQAqAvQFlEEAKgKsAyBaQQAqAvAEkpSTlJMha0EAIGu8QYCAgPwHcQR9IGsFQwAAAAALOALwBUEAKgLwBUEAKgLMBEEAKgKEBUEAKgKABpRBACoC3AFBACoC/AWUkpSTIWxBACBsvEGAgID8B3EEfSBsBUMAAAAACzgC+AVBACoCgAZBACoC+AVDAAAAQEEAKgL8BZSSkiFtQQAgbTgChAZBACoCzARBACoC6AUgbZRBACoCjAZBACoCiAaUkpRBACoCkAZBACoCmAaUkyFuQQAgbrxBgICA/AdxBH0gbgVDAAAAAAs4ApQGQQAqApQGQQAqAuQFQQAqApwGQQAqAqgGlEEAKgKMAkEAKgKkBpSSlJMhb0EAIG+8QYCAgPwHcQR9IG8FQwAAAAALOAKgBkEAKgK8AkEAKgK0BpQhcEEAKgLkBUEAKgKIAkEAKgKgBpRBACoCrAZBACoCpAaUkkEAKgKIAkEAKgKoBpSSlEEAKgKoAkEAKgKwAkEAKgK4BpQgcJKUkyFxQQAgcbxBgICA/AdxBH0gcQVDAAAAAAs4ArAGQQAqAuwCQQAqAsAGlCFyQQAqArgGQQAqAqgCIHBBACoCsAJBACoCsAaUkpSSQQAqAtgCQQAqAuACQQAqAsQGlCBykpSTIXNBACBzvEGAgID8B3EEfSBzBUMAAAAACzgCvAZBACoCxAZBACoC2AIgckEAKgLgAkEAKgK8BpSSlJIhdCAlQQAqAswGlCAoIHSLlJIhdUEAIHW8QYCAgPwHcQR9IHUFQwAAAAALOALIBkEAKgLIBiF2IHa8QYCAgPwHcQR9IHYFQwAAAAALIXcgdyApXiEWQQAgFjYC0AYgCSAWQQAoAtQGSGwhF0EAKALcBkF/aiEYQQAgFyAYSAR/IBgFIBcLNgLYBiAWskEAKALYBkEASrKXiyF4QQAqAuwGIHheBH0gKwUgKgsheUEAKgLkBiB5lCB4QwAAgD8geZOUkiF6QQAgerxBgICA/AdxBH0gegVDAAAAAAs4AuAGQQAqAuAGIXtBACB7vEGAgID8B3EEfSB7BUMAAAAACzgC6AZDAAAAAEEAKgL4BkEAKgL8AUEAKgKAB5RBACoCzAQgbUEAKgKIBpKUk5STIXxBACB8vEGAgID8B3EEfSB8BUMAAAAACzgC/AZBACoC/AZBACoC5AVBACoCnAZBACoCjAeUQQAqAowCQQAqAogHlJKUkyF9QQAgfbxBgICA/AdxBH0gfQVDAAAAAAs4AoQHQQAqAowHQQAqAoQHQwAAAEBBACoCiAeUkpIhfkEAIH44ApAHQQAqAuQFQQAqAvQGIH6UQQAqApgHQQAqApQHlJKUQQAqApwHQQAqAqQHlJMhf0EAIH+8QYCAgPwHcQR9IH8FQwAAAAALOAKgB0EAKgKgB0EAKgLwBkEAKgKoB0EAKgK0B5RBACoCvAJBACoCsAeUkpSTIYABQQAggAG8QYCAgPwHcQR9IIABBUMAAAAACzgCrAdBACoC7AJBACoCwAeUIYEBQQAqAvAGQQAqArgCQQAqAqwHlEEAKgK4B0EAKgKwB5SSQQAqArgCQQAqArQHlJKUQQAqAtgCQQAqAuACQQAqAsQHlCCBAZKUkyGCAUEAIIIBvEGAgID8B3EEfSCCAQVDAAAAAAs4ArwHQQAqAsQHQQAqAtgCIIEBQQAqAuACQQAqArwHlJKUkiGDASAlQQAqAswHlCAoIIMBi5SSIYQBQQAghAG8QYCAgPwHcQR9IIQBBUMAAAAACzgCyAdBACoCyAchhQEghQG8QYCAgPwHcQR9IIUBBUMAAAAACyGGASCGASApXiEZQQAgGTYC0AcgCSAZQQAoAtQHSGwhGkEAKALcB0F/aiEbQQAgGiAbSAR/IBsFIBoLNgLYByAZskEAKALYB0EASrKXiyGHAUEAKgLsByCHAV4EfSArBSAqCyGIAUEAKgLkByCIAZQghwFDAACAPyCIAZOUkiGJAUEAIIkBvEGAgID8B3EEfSCJAQVDAAAAAAs4AuAHQQAqAuAHIYoBQQAgigG8QYCAgPwHcQR9IIoBBUMAAAAACzgC6AdDAAAAAEEAKgL4B0EAKgKsAkEAKgKACJRBACoC5AUgfkEAKgKUB5KUk5STIYsBQQAgiwG8QYCAgPwHcQR9IIsBBUMAAAAACzgC/AdBACoC/AdBACoC8AZBACoCqAdBACoCjAiUQQAqArwCQQAqAogIlJKUkyGMAUEAIIwBvEGAgID8B3EEfSCMAQVDAAAAAAs4AoQIQQAqAowIQQAqAoQIQwAAAEBBACoCiAiUkpIhjQFBACCNATgCkAhBACoC8AZBACoC9AcgjQGUQQAqApgIQQAqApQIlJKUQQAqApwIQQAqAqQIlJMhjgFBACCOAbxBgICA/AdxBH0gjgEFQwAAAAALOAKgCEEAKgKgCEEAKgLwB0EAKgKoCEEAKgK0CJRBACoC7AJBACoCsAiUkpSTIY8BQQAgjwG8QYCAgPwHcQR9II8BBUMAAAAACzgCrAhBACoC6AJBACoCrAiUQQAqArgIQQAqArAIlJJBACoC6AJBACoCtAiUkiGQASAlQQAqAsAIlCAoQQAqAvAHIJABlIuUkiGRAUEAIJEBvEGAgID8B3EEfSCRAQVDAAAAAAs4ArwIQQAqArwIIZIBIJIBvEGAgID8B3EEfSCSAQVDAAAAAAshkwEgkwEgKV4hHEEAIBw2AsQIIAkgHEEAKALICEhsIR1BACgC0AhBf2ohHkEAIB0gHkgEfyAeBSAdCzYCzAggHLJBACgCzAhBAEqyl4shlAFBACoC4AgglAFeBH0gKwUgKgshlQFBACoC2AgglQGUIJQBQwAAgD8glQGTlJIhlgFBACCWAbxBgICA/AdxBH0glgEFQwAAAAALOALUCEEAKgLUCCGXAUEAIJcBvEGAgID8B3EEfSCXAQVDAAAAAAs4AtwIQwAAAABBACoC5AhBACoC3AJBACoC7AiUQQAqAvAGII0BQQAqApQIkpSTlJMhmAFBACCYAbxBgICA/AdxBH0gmAEFQwAAAAALOALoCEEAKgLoCEEAKgLwB0EAKgKoCEEAKgL4CJRBACoC7AJBACoC9AiUkpSTIZkBQQAgmQG8QYCAgPwHcQR9IJkBBUMAAAAACzgC8AhBACoC+AhBACoC8AhDAAAAQEEAKgL0CJSSkiGaASAlQQAqAoAJlCAoQQAqAvAHIJoBlIuUkiGbAUEAIJsBvEGAgID8B3EEfSCbAQVDAAAAAAs4AvwIQQAqAvwIIZwBIJwBvEGAgID8B3EEfSCcAQVDAAAAAAshnQEgnQEgKV4hH0EAIB82AoQJIAkgH0EAKAKICUhsISBBACgCkAlBf2ohIUEAICAgIUgEfyAhBSAgCzYCjAkgH7JBACgCjAlBAEqyl4shngFBACoCoAkgngFeBH0gKwUgKgshnwFBACoCmAkgnwGUIJ4BQwAAgD8gnwGTlJIhoAFBACCgAbxBgICA/AdxBH0goAEFQwAAAAALOAKUCUEAKgKUCSGhAUEAIKEBvEGAgID8B3EEfSChAQVDAAAAAAs4ApwJQQAqAqQDIDuUQQAqAsQEIFCUkkEAKgLcBSBjlJJBACoC6AYgdJSSQQAqAugHIIMBlJJBACoC8AdBACoC3AggkAGUQQAqApwJIJoBlJKUkiGiASAGIAxqIKIBOAIAIAcgDGogogE4AgBBAEEAKgJEOAJIQQBBACoCVDgCWEEAQQAqAlw4AmBBAEEAKgJsOAJwQQBBACoCgAE4AoQBQQBBACoCfDgCgAFBAEEAKgK0ATgCuAFBAEEAKgKwATgCtAFBAEEAKgLkATgC6AFBAEEAKgLgATgC5AFBAEEAKgKUAjgCmAJBAEEAKgKQAjgClAJBAEEAKgLEAjgCyAJBAEEAKgLAAjgCxAJBAEEAKgL0AjgC+AJBAEEAKgLwAjgC9AJBAEEAKgL8AjgCgANBAEEAKAKIAzYCjANBAEEAKAKUAzYCmANBAEEAKgKcAzgCoANBAEEAKgKkAzgCqANBAEEAKgK0AzgCuANBAEEAKgLAAzgCxANBAEEAKgK8AzgCwANBAEEAKgLIAzgCzANBAEEAKgLYAzgC3ANBAEEAKgLoAzgC7ANBAEEAKgLkAzgC6ANBAEEAKgL4AzgC/ANBAEEAKgL0AzgC+ANBAEEAKgKEBDgCiARBAEEAKgKABDgChARBAEEAKgKQBDgClARBAEEAKgKMBDgCkARBAEEAKgKcBDgCoARBAEEAKgKYBDgCnARBAEEAKgKkBDgCqARBAEEAKAKsBDYCsARBAEEAKAK0BDYCuARBAEEAKgK8BDgCwARBAEEAKgLEBDgCyARBAEEAKgLYBDgC3ARBAEEAKgLkBDgC6ARBAEEAKgLgBDgC5ARBAEEAKgLsBDgC8ARBAEEAKgL8BDgCgAVBAEEAKgKMBTgCkAVBAEEAKgKIBTgCjAVBAEEAKgKcBTgCoAVBAEEAKgKYBTgCnAVBAEEAKgKoBTgCrAVBAEEAKgKkBTgCqAVBAEEAKgK0BTgCuAVBAEEAKgKwBTgCtAVBAEEAKgK8BTgCwAVBAEEAKALEBTYCyAVBAEEAKALMBTYC0AVBAEEAKgLUBTgC2AVBAEEAKgLcBTgC4AVBAEEAKgLwBTgC9AVBAEEAKgL8BTgCgAZBAEEAKgL4BTgC/AVBAEEAKgKEBjgCiAZBAEEAKgKUBjgCmAZBAEEAKgKkBjgCqAZBAEEAKgKgBjgCpAZBAEEAKgK0BjgCuAZBAEEAKgKwBjgCtAZBAEEAKgLABjgCxAZBAEEAKgK8BjgCwAZBAEEAKgLIBjgCzAZBAEEAKALQBjYC1AZBAEEAKALYBjYC3AZBAEEAKgLgBjgC5AZBAEEAKgLoBjgC7AZBAEEAKgL8BjgCgAdBAEEAKgKIBzgCjAdBAEEAKgKEBzgCiAdBAEEAKgKQBzgClAdBAEEAKgKgBzgCpAdBAEEAKgKwBzgCtAdBAEEAKgKsBzgCsAdBAEEAKgLABzgCxAdBAEEAKgK8BzgCwAdBAEEAKgLIBzgCzAdBAEEAKALQBzYC1AdBAEEAKALYBzYC3AdBAEEAKgLgBzgC5AdBAEEAKgLoBzgC7AdBAEEAKgL8BzgCgAhBAEEAKgKICDgCjAhBAEEAKgKECDgCiAhBAEEAKgKQCDgClAhBAEEAKgKgCDgCpAhBAEEAKgKwCDgCtAhBAEEAKgKsCDgCsAhBAEEAKgK8CDgCwAhBAEEAKALECDYCyAhBAEEAKALMCDYC0AhBAEEAKgLUCDgC2AhBAEEAKgLcCDgC4AhBAEEAKgLoCDgC7AhBAEEAKgL0CDgC+AhBAEEAKgLwCDgC9AhBAEEAKgL8CDgCgAlBAEEAKAKECTYCiAlBAEEAKAKMCTYCkAlBAEEAKgKUCTgCmAlBAEEAKgKcCTgCoAkgDEEEaiEMIAxBBCABbEgEQAwCDAELCwsLhYCAgAAAQQIPC4WAgIAAAEECDwuLgICAAAAgACABaioCAA8LiICAgAAAQQAoAggPC46AgIAAACAAIAEQAyAAIAEQDAven4CAAAFSf0EAIQFBACECQQAhA0EAIQRBACEFQQAhBkEAIQdBACEIQQAhCUEAIQpBACELQQAhDEEAIQ1BACEOQQAhD0EAIRBBACERQQAhEkEAIRNBACEUQQAhFUEAIRZBACEXQQAhGEEAIRlBACEaQQAhG0EAIRxBACEdQQAhHkEAIR9BACEgQQAhIUEAISJBACEjQQAhJEEAISVBACEmQQAhJ0EAIShBACEpQQAhKkEAIStBACEsQQAhLUEAIS5BACEvQQAhMEEAITFBACEyQQAhM0EAITRBACE1QQAhNkEAITdBACE4QQAhOUEAITpBACE7QQAhPEEAIT1BACE+QQAhP0EAIUBBACFBQQAhQkEAIUNBACFEQQAhRUEAIUZBACFHQQAhSEEAIUlBACFKQQAhS0EAIUxBACFNQQAhTkEAIU9BACFQQQAhUUEAIVJBACEBA0ACQEHEACABQQJ0akMAAAAAOAIAIAFBAWohASABQQJIBEAMAgwBCwsLQQAhAgNAAkBB1AAgAkECdGpDAAAAADgCACACQQFqIQIgAkECSARADAIMAQsLC0EAIQMDQAJAQdwAIANBAnRqQwAAAAA4AgAgA0EBaiEDIANBAkgEQAwCDAELCwtBACEEA0ACQEHsACAEQQJ0akMAAAAAOAIAIARBAWohBCAEQQJIBEAMAgwBCwsLQQAhBQNAAkBB/AAgBUECdGpDAAAAADgCACAFQQFqIQUgBUEDSARADAIMAQsLC0EAIQYDQAJAQbABIAZBAnRqQwAAAAA4AgAgBkEBaiEGIAZBA0gEQAwCDAELCwtBACEHA0ACQEHgASAHQQJ0akMAAAAAOAIAIAdBAWohByAHQQNIBEAMAgwBCwsLQQAhCANAAkBBkAIgCEECdGpDAAAAADgCACAIQQFqIQggCEEDSARADAIMAQsLC0EAIQkDQAJAQcACIAlBAnRqQwAAAAA4AgAgCUEBaiEJIAlBA0gEQAwCDAELCwtBACEKA0ACQEHwAiAKQQJ0akMAAAAAOAIAIApBAWohCiAKQQNIBEAMAgwBCwsLQQAhCwNAAkBB/AIgC0ECdGpDAAAAADgCACALQQFqIQsgC0ECSARADAIMAQsLC0EAIQwDQAJAQYgDIAxBAnRqQQA2AgAgDEEBaiEMIAxBAkgEQAwCDAELCwtBACENA0ACQEGUAyANQQJ0akEANgIAIA1BAWohDSANQQJIBEAMAgwBCwsLQQAhDgNAAkBBnAMgDkECdGpDAAAAADgCACAOQQFqIQ4gDkECSARADAIMAQsLC0EAIQ8DQAJAQaQDIA9BAnRqQwAAAAA4AgAgD0EBaiEPIA9BAkgEQAwCDAELCwtBACEQA0ACQEG0AyAQQQJ0akMAAAAAOAIAIBBBAWohECAQQQJIBEAMAgwBCwsLQQAhEQNAAkBBvAMgEUECdGpDAAAAADgCACARQQFqIREgEUEDSARADAIMAQsLC0EAIRIDQAJAQcgDIBJBAnRqQwAAAAA4AgAgEkEBaiESIBJBAkgEQAwCDAELCwtBACETA0ACQEHYAyATQQJ0akMAAAAAOAIAIBNBAWohEyATQQJIBEAMAgwBCwsLQQAhFANAAkBB5AMgFEECdGpDAAAAADgCACAUQQFqIRQgFEEDSARADAIMAQsLC0EAIRUDQAJAQfQDIBVBAnRqQwAAAAA4AgAgFUEBaiEVIBVBA0gEQAwCDAELCwtBACEWA0ACQEGABCAWQQJ0akMAAAAAOAIAIBZBAWohFiAWQQNIBEAMAgwBCwsLQQAhFwNAAkBBjAQgF0ECdGpDAAAAADgCACAXQQFqIRcgF0EDSARADAIMAQsLC0EAIRgDQAJAQZgEIBhBAnRqQwAAAAA4AgAgGEEBaiEYIBhBA0gEQAwCDAELCwtBACEZA0ACQEGkBCAZQQJ0akMAAAAAOAIAIBlBAWohGSAZQQJIBEAMAgwBCwsLQQAhGgNAAkBBrAQgGkECdGpBADYCACAaQQFqIRogGkECSARADAIMAQsLC0EAIRsDQAJAQbQEIBtBAnRqQQA2AgAgG0EBaiEbIBtBAkgEQAwCDAELCwtBACEcA0ACQEG8BCAcQQJ0akMAAAAAOAIAIBxBAWohHCAcQQJIBEAMAgwBCwsLQQAhHQNAAkBBxAQgHUECdGpDAAAAADgCACAdQQFqIR0gHUECSARADAIMAQsLC0EAIR4DQAJAQdgEIB5BAnRqQwAAAAA4AgAgHkEBaiEeIB5BAkgEQAwCDAELCwtBACEfA0ACQEHgBCAfQQJ0akMAAAAAOAIAIB9BAWohHyAfQQNIBEAMAgwBCwsLQQAhIANAAkBB7AQgIEECdGpDAAAAADgCACAgQQFqISAgIEECSARADAIMAQsLC0EAISEDQAJAQfwEICFBAnRqQwAAAAA4AgAgIUEBaiEhICFBAkgEQAwCDAELCwtBACEiA0ACQEGIBSAiQQJ0akMAAAAAOAIAICJBAWohIiAiQQNIBEAMAgwBCwsLQQAhIwNAAkBBmAUgI0ECdGpDAAAAADgCACAjQQFqISMgI0EDSARADAIMAQsLC0EAISQDQAJAQaQFICRBAnRqQwAAAAA4AgAgJEEBaiEkICRBA0gEQAwCDAELCwtBACElA0ACQEGwBSAlQQJ0akMAAAAAOAIAICVBAWohJSAlQQNIBEAMAgwBCwsLQQAhJgNAAkBBvAUgJkECdGpDAAAAADgCACAmQQFqISYgJkECSARADAIMAQsLC0EAIScDQAJAQcQFICdBAnRqQQA2AgAgJ0EBaiEnICdBAkgEQAwCDAELCwtBACEoA0ACQEHMBSAoQQJ0akEANgIAIChBAWohKCAoQQJIBEAMAgwBCwsLQQAhKQNAAkBB1AUgKUECdGpDAAAAADgCACApQQFqISkgKUECSARADAIMAQsLC0EAISoDQAJAQdwFICpBAnRqQwAAAAA4AgAgKkEBaiEqICpBAkgEQAwCDAELCwtBACErA0ACQEHwBSArQQJ0akMAAAAAOAIAICtBAWohKyArQQJIBEAMAgwBCwsLQQAhLANAAkBB+AUgLEECdGpDAAAAADgCACAsQQFqISwgLEEDSARADAIMAQsLC0EAIS0DQAJAQYQGIC1BAnRqQwAAAAA4AgAgLUEBaiEtIC1BAkgEQAwCDAELCwtBACEuA0ACQEGUBiAuQQJ0akMAAAAAOAIAIC5BAWohLiAuQQJIBEAMAgwBCwsLQQAhLwNAAkBBoAYgL0ECdGpDAAAAADgCACAvQQFqIS8gL0EDSARADAIMAQsLC0EAITADQAJAQbAGIDBBAnRqQwAAAAA4AgAgMEEBaiEwIDBBA0gEQAwCDAELCwtBACExA0ACQEG8BiAxQQJ0akMAAAAAOAIAIDFBAWohMSAxQQNIBEAMAgwBCwsLQQAhMgNAAkBByAYgMkECdGpDAAAAADgCACAyQQFqITIgMkECSARADAIMAQsLC0EAITMDQAJAQdAGIDNBAnRqQQA2AgAgM0EBaiEzIDNBAkgEQAwCDAELCwtBACE0A0ACQEHYBiA0QQJ0akEANgIAIDRBAWohNCA0QQJIBEAMAgwBCwsLQQAhNQNAAkBB4AYgNUECdGpDAAAAADgCACA1QQFqITUgNUECSARADAIMAQsLC0EAITYDQAJAQegGIDZBAnRqQwAAAAA4AgAgNkEBaiE2IDZBAkgEQAwCDAELCwtBACE3A0ACQEH8BiA3QQJ0akMAAAAAOAIAIDdBAWohNyA3QQJIBEAMAgwBCwsLQQAhOANAAkBBhAcgOEECdGpDAAAAADgCACA4QQFqITggOEEDSARADAIMAQsLC0EAITkDQAJAQZAHIDlBAnRqQwAAAAA4AgAgOUEBaiE5IDlBAkgEQAwCDAELCwtBACE6A0ACQEGgByA6QQJ0akMAAAAAOAIAIDpBAWohOiA6QQJIBEAMAgwBCwsLQQAhOwNAAkBBrAcgO0ECdGpDAAAAADgCACA7QQFqITsgO0EDSARADAIMAQsLC0EAITwDQAJAQbwHIDxBAnRqQwAAAAA4AgAgPEEBaiE8IDxBA0gEQAwCDAELCwtBACE9A0ACQEHIByA9QQJ0akMAAAAAOAIAID1BAWohPSA9QQJIBEAMAgwBCwsLQQAhPgNAAkBB0AcgPkECdGpBADYCACA+QQFqIT4gPkECSARADAIMAQsLC0EAIT8DQAJAQdgHID9BAnRqQQA2AgAgP0EBaiE/ID9BAkgEQAwCDAELCwtBACFAA0ACQEHgByBAQQJ0akMAAAAAOAIAIEBBAWohQCBAQQJIBEAMAgwBCwsLQQAhQQNAAkBB6AcgQUECdGpDAAAAADgCACBBQQFqIUEgQUECSARADAIMAQsLC0EAIUIDQAJAQfwHIEJBAnRqQwAAAAA4AgAgQkEBaiFCIEJBAkgEQAwCDAELCwtBACFDA0ACQEGECCBDQQJ0akMAAAAAOAIAIENBAWohQyBDQQNIBEAMAgwBCwsLQQAhRANAAkBBkAggREECdGpDAAAAADgCACBEQQFqIUQgREECSARADAIMAQsLC0EAIUUDQAJAQaAIIEVBAnRqQwAAAAA4AgAgRUEBaiFFIEVBAkgEQAwCDAELCwtBACFGA0ACQEGsCCBGQQJ0akMAAAAAOAIAIEZBAWohRiBGQQNIBEAMAgwBCwsLQQAhRwNAAkBBvAggR0ECdGpDAAAAADgCACBHQQFqIUcgR0ECSARADAIMAQsLC0EAIUgDQAJAQcQIIEhBAnRqQQA2AgAgSEEBaiFIIEhBAkgEQAwCDAELCwtBACFJA0ACQEHMCCBJQQJ0akEANgIAIElBAWohSSBJQQJIBEAMAgwBCwsLQQAhSgNAAkBB1AggSkECdGpDAAAAADgCACBKQQFqIUogSkECSARADAIMAQsLC0EAIUsDQAJAQdwIIEtBAnRqQwAAAAA4AgAgS0EBaiFLIEtBAkgEQAwCDAELCwtBACFMA0ACQEHoCCBMQQJ0akMAAAAAOAIAIExBAWohTCBMQQJIBEAMAgwBCwsLQQAhTQNAAkBB8AggTUECdGpDAAAAADgCACBNQQFqIU0gTUEDSARADAIMAQsLC0EAIU4DQAJAQfwIIE5BAnRqQwAAAAA4AgAgTkEBaiFOIE5BAkgEQAwCDAELCwtBACFPA0ACQEGECSBPQQJ0akEANgIAIE9BAWohTyBPQQJIBEAMAgwBCwsLQQAhUANAAkBBjAkgUEECdGpBADYCACBQQQFqIVAgUEECSARADAIMAQsLC0EAIVEDQAJAQZQJIFFBAnRqQwAAAAA4AgAgUUEBaiFRIFFBAkgEQAwCDAELCwtBACFSA0ACQEGcCSBSQQJ0akMAAAAAOAIAIFJBAWohUiBSQQJIBEAMAgwBCwsLC6qRgIAAAEEAIAE2AghBAEMAgDtIQwAAgD9BACgCCLKXljgCDEEAQwAAgD9BACoCDJU4AhBBAEOUnutFQQAqAgyVEAI4AhRBAEMAAIA/QQAqAhSVOAIYQQBDAACAP0EAKgIYQwAAgD+SQQAqAhSVQwAAgD+SlTgCHEEAQQAqAhRDAAAAQBABOAIgQQBDAACAP0EAKgIglTgCJEEAQQAqAhhDAACAP5I4AihBAEMAAAAAQwAAgD9BACoCFEEAKgIolJWTOAIsQQBD0VP7QUEAKgIMlRACOAI0QQBDAACAP0EAKgI0lTgCOEEAQQAqAjhDAACAP5I4AjxBAEMAAAAAQwAAgD9BACoCNEEAKgI8lJWTOAJAQQBDAACAP0EAKgI8lTgCTEEAQwAAgD9BACoCOJM4AlBBAEMAAIA/QQAqAiiVOAJkQQBDAACAP0EAKgIYkzgCaEEAQQAqAhhDAACAv5JBACoCFJVDAACAP5I4AnRBAEMAAABAQwAAgD9BACoCJJOUOAJ4QQBDAAAAAEMAAABAQQAqAiCVkzgCiAFBAEOUnmtFQQAqAgyVEAI4AowBQQBDAACAP0EAKgKMAZU4ApABQQBBACoCkAFDAACAP5I4ApQBQQBDAACAP0EAKgKUAUEAKgKMAZVDAACAP5KVOAKYAUEAQwAAgD9BACoCkAGTOAKcAUEAQwAAgD9BACoCnAFBACoCjAGVkzgCoAFBAEEAKgKMAUMAAABAEAE4AqQBQQBDAACAP0EAKgKkAZU4AqgBQQBDAAAAQEMAAIA/QQAqAqgBk5Q4AqwBQQBDlJ7rREEAKgIMlRACOAK8AUEAQwAAgD9BACoCvAGVOALAAUEAQQAqAsABQwAAgD+SOALEAUEAQwAAgD9BACoCxAFBACoCvAGVQwAAgD+SlTgCyAFBAEMAAIA/QQAqAsABkzgCzAFBAEMAAIA/QQAqAswBQQAqArwBlZM4AtABQQBBACoCvAFDAAAAQBABOALUAUEAQwAAgD9BACoC1AGVOALYAUEAQwAAAEBDAACAP0EAKgLYAZOUOALcAUEAQ5Sea0RBACoCDJUQAjgC7AFBAEMAAIA/QQAqAuwBlTgC8AFBAEEAKgLwAUMAAIA/kjgC9AFBAEMAAIA/QQAqAvQBQQAqAuwBlUMAAIA/kpU4AvgBQQBDAACAP0EAKgLwAZM4AvwBQQBDAACAP0EAKgL8AUEAKgLsAZWTOAKAAkEAQQAqAuwBQwAAAEAQATgChAJBAEMAAIA/QQAqAoQClTgCiAJBAEMAAABAQwAAgD9BACoCiAKTlDgCjAJBAEOUnutDQQAqAgyVEAI4ApwCQQBDAACAP0EAKgKcApU4AqACQQBBACoCoAJDAACAP5I4AqQCQQBDAACAP0EAKgKkAkEAKgKcApVDAACAP5KVOAKoAkEAQwAAgD9BACoCoAKTOAKsAkEAQwAAgD9BACoCrAJBACoCnAKVkzgCsAJBAEEAKgKcAkMAAABAEAE4ArQCQQBDAACAP0EAKgK0ApU4ArgCQQBDAAAAQEMAAIA/QQAqArgCk5Q4ArwCQQBDGjRMQ0EAKgIMlRACOALMAkEAQwAAgD9BACoCzAKVOALQAkEAQQAqAtACQwAAgD+SOALUAkEAQwAAgD9BACoC1AJBACoCzAKVQwAAgD+SlTgC2AJBAEMAAIA/QQAqAtACkzgC3AJBAEMAAIA/QQAqAtwCQQAqAswClZM4AuACQQBBACoCzAJDAAAAQBABOALkAkEAQwAAgD9BACoC5AKVOALoAkEAQwAAAEBDAACAP0EAKgLoApOUOALsAkEAQwAAgD9BACoCkAFDAACAP5JBACoCjAGVQwAAgD+SlTgCrANBAEMAAIA/QQAqAowBQQAqApQBlJU4ArADQQBDAAAAAEEAKgKwA5M4AtADQQBBACoCnAFBACoClAGVOALUA0EAQQAqApABQwAAgL+SQQAqAowBlUMAAIA/kjgC4ANBAEMAAAAAQwAAAEBBACoCpAGVkzgC8ANBAEMAAIA/QQAqAsABQwAAgD+SQQAqArwBlUMAAIA/kpU4AswEQQBDAACAP0EAKgK8AUEAKgLEAZSVOALQBEEAQwAAgD9BACoClAGVOALUBEEAQwAAAABBACoC0ASTOAL0BEEAQQAqAswBQQAqAsQBlTgC+ARBAEEAKgLAAUMAAIC/kkEAKgK8AZVDAACAP5I4AoQFQQBDAAAAAEMAAABAQQAqAtQBlZM4ApQFQQBDAACAP0EAKgLwAUMAAIA/kkEAKgLsAZVDAACAP5KVOALkBUEAQwAAgD9BACoC7AFBACoC9AGUlTgC6AVBAEMAAIA/QQAqAsQBlTgC7AVBAEMAAAAAQQAqAugFkzgCjAZBAEEAKgL8AUEAKgL0AZU4ApAGQQBBACoC8AFDAACAv5JBACoC7AGVQwAAgD+SOAKcBkEAQwAAAABDAAAAQEEAKgKEApWTOAKsBkEAQwAAgD9BACoCoAJDAACAP5JBACoCnAKVQwAAgD+SlTgC8AZBAEMAAIA/QQAqApwCQQAqAqQClJU4AvQGQQBDAACAP0EAKgL0AZU4AvgGQQBDAAAAAEEAKgL0BpM4ApgHQQBBACoCrAJBACoCpAKVOAKcB0EAQQAqAqACQwAAgL+SQQAqApwClUMAAIA/kjgCqAdBAEMAAAAAQwAAAEBBACoCtAKVkzgCuAdBAEMAAIA/QQAqAtACQwAAgD+SQQAqAswClUMAAIA/kpU4AvAHQQBDAACAP0EAKgLMAkEAKgLUApSVOAL0B0EAQwAAgD9BACoCpAKVOAL4B0EAQwAAAABBACoC9AeTOAKYCEEAQQAqAtwCQQAqAtQClTgCnAhBAEEAKgLQAkMAAIC/kkEAKgLMApVDAACAP5I4AqgIQQBDAAAAAEMAAABAQQAqAuQClZM4ArgIQQBDAACAP0EAKgLUApU4AuQIC5CAgIAAACAAIAEQCyAAEA0gABAKC7aAgIAAAEEAQwrXIzw4AgBBAEMK16M8OAIEQQBDAADwwjgCMEEAQwAA8MI4AoQDQQBDzczMPTgCkAMLkICAgAAAIAAgAUgEfyABBSAACw8LkICAgAAAIAAgAUgEfyAABSABCw8LjICAgAAAIAAgAWogAjgCAAsL/qOAgAABAEEAC/cjeyJuYW1lIjogIkRlYWRHYXRlV2l0aFBhcmFtcyIsImZpbGVuYW1lIjogIkRlYWRHYXRlV2l0aFBhcmFtcy5kc3AiLCJ2ZXJzaW9uIjogIjIuMjguOCIsImNvbXBpbGVfb3B0aW9ucyI6ICItbGFuZyB3YXNtLWliIC1zY2FsIC1mdHogMiIsImluY2x1ZGVfcGF0aG5hbWVzIjogWyIvdXNyL2xvY2FsL3NoYXJlL2ZhdXN0IiwiL3Vzci9sb2NhbC9zaGFyZS9mYXVzdCIsIi91c3Ivc2hhcmUvZmF1c3QiLCIuIiwiL3RtcC9zZXNzaW9ucy82MkNBNjQ5MTQ0Q0VFNTA2MUI3N0FEMzE2MDA1RDEzOUUxMkMxRjNEL3dlYi93YXAiXSwic2l6ZSI6IDExODgsImlucHV0cyI6IDIsIm91dHB1dHMiOiAyLCJtZXRhIjogWyB7ICJhbmFseXplcnNfbGliX25hbWUiOiAiRmF1c3QgQW5hbHl6ZXIgTGlicmFyeSIgfSx7ICJhbmFseXplcnNfbGliX3ZlcnNpb24iOiAiMC4xIiB9LHsgImF1dGhvciI6ICJPbGVnIEthcGl0b25vdiIgfSx7ICJiYXNpY3NfbGliX25hbWUiOiAiRmF1c3QgQmFzaWMgRWxlbWVudCBMaWJyYXJ5IiB9LHsgImJhc2ljc19saWJfdmVyc2lvbiI6ICIwLjEiIH0seyAiY29tcGlsYXRpb25fb3B0aW9ucyI6ICItc2luZ2xlIC1zY2FsIC1JIGxpYnJhcmllcy8gLUkgcHJvamVjdC8gLWxhbmcgd2FzbSIgfSx7ICJmaWxlbmFtZSI6ICJEZWFkR2F0ZVdpdGhQYXJhbXMuZHNwIiB9LHsgImZpbHRlcnNfbGliX2ZpbHRlcmJhbmtfYXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVyc19saWJfZmlsdGVyYmFua19jb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zQGNjcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVyc19saWJfZmlsdGVyYmFua19saWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVyc19saWJfZmlyX2F1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnNfbGliX2Zpcl9jb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zQGNjcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVyc19saWJfZmlyX2xpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzX2xpYl9oaWdocGFzc19hdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzX2xpYl9oaWdocGFzc19jb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zQGNjcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVyc19saWJfaGlnaHBhc3NfcGx1c19sb3dwYXNzX2F1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnNfbGliX2hpZ2hwYXNzX3BsdXNfbG93cGFzc19jb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zQGNjcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVyc19saWJfaGlnaHBhc3NfcGx1c19sb3dwYXNzX2xpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzX2xpYl9paXJfYXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVyc19saWJfaWlyX2NvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NAY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzX2xpYl9paXJfbGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnNfbGliX2xvd3Bhc3MwX2hpZ2hwYXNzMSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnNfbGliX2xvd3Bhc3MwX2hpZ2hwYXNzMV9hdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzX2xpYl9sb3dwYXNzX2F1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnNfbGliX2xvd3Bhc3NfY29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc0BjY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnNfbGliX2xvd3Bhc3NfbGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnNfbGliX25hbWUiOiAiRmF1c3QgRmlsdGVycyBMaWJyYXJ5IiB9LHsgImZpbHRlcnNfbGliX3RmMV9hdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzX2xpYl90ZjFfY29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc0BjY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnNfbGliX3RmMV9saWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVyc19saWJfdGYxc19hdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzX2xpYl90ZjFzX2NvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NAY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzX2xpYl90ZjFzX2xpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzX2xpYl90ZjJfYXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVyc19saWJfdGYyX2NvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NAY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzX2xpYl90ZjJfbGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnNfbGliX3RmMnNfYXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVyc19saWJfdGYyc19jb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zQGNjcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVyc19saWJfdGYyc19saWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAibGlicmFyeV9wYXRoIjogIkZhdXN0RFNQIiB9LHsgImxpY2Vuc2UiOiAiR1BMdjMiIH0seyAibWF0aHNfbGliX2F1dGhvciI6ICJHUkFNRSIgfSx7ICJtYXRoc19saWJfY29weXJpZ2h0IjogIkdSQU1FIiB9LHsgIm1hdGhzX2xpYl9saWNlbnNlIjogIkxHUEwgd2l0aCBleGNlcHRpb24iIH0seyAibWF0aHNfbGliX25hbWUiOiAiRmF1c3QgTWF0aCBMaWJyYXJ5IiB9LHsgIm1hdGhzX2xpYl92ZXJzaW9uIjogIjIuMyIgfSx7ICJtaXNjZWZmZWN0c19saWJfbmFtZSI6ICJNaXNjIEVmZmVjdHMgTGlicmFyeSIgfSx7ICJtaXNjZWZmZWN0c19saWJfdmVyc2lvbiI6ICIyLjAiIH0seyAibmFtZSI6ICJEZWFkR2F0ZVdpdGhQYXJhbXMiIH0seyAicGxhdGZvcm1fbGliX25hbWUiOiAiR2VuZXJpYyBQbGF0Zm9ybSBMaWJyYXJ5IiB9LHsgInBsYXRmb3JtX2xpYl92ZXJzaW9uIjogIjAuMSIgfSx7ICJzaWduYWxzX2xpYl9uYW1lIjogIkZhdXN0IFNpZ25hbCBSb3V0aW5nIExpYnJhcnkiIH0seyAic2lnbmFsc19saWJfdmVyc2lvbiI6ICIwLjAiIH0seyAidmVyc2lvbiI6ICIwLjFiIiB9XSwidWkiOiBbIHsidHlwZSI6ICJ2Z3JvdXAiLCJsYWJlbCI6ICJEZWFkR2F0ZVdpdGhQYXJhbXMiLCJpdGVtcyI6IFsgeyJ0eXBlIjogInZzbGlkZXIiLCJsYWJlbCI6ICJBdHRhY2siLCJhZGRyZXNzIjogIi9EZWFkR2F0ZVdpdGhQYXJhbXMvQXR0YWNrIiwiaW5kZXgiOiAwLCJtZXRhIjogW3sgInN0eWxlIjogImtub2IiIH0seyAidW5pdCI6ICJzIiB9XSwiaW5pdCI6IDAuMDEsIm1pbiI6IDAsIm1heCI6IDAuMDQsInN0ZXAiOiAwLjAwMX0seyJ0eXBlIjogInZzbGlkZXIiLCJsYWJlbCI6ICJEZWFkIFpvbmUiLCJhZGRyZXNzIjogIi9EZWFkR2F0ZVdpdGhQYXJhbXMvRGVhZF9ab25lIiwiaW5kZXgiOiA0OCwibWV0YSI6IFt7ICJzdHlsZSI6ICJrbm9iIiB9XSwiaW5pdCI6IC0xMjAsIm1pbiI6IC0xMjAsIm1heCI6IDAsInN0ZXAiOiAwLjAwMX0seyJ0eXBlIjogInZzbGlkZXIiLCJsYWJlbCI6ICJIb2xkIiwiYWRkcmVzcyI6ICIvRGVhZEdhdGVXaXRoUGFyYW1zL0hvbGQiLCJpbmRleCI6IDQwMCwibWV0YSI6IFt7ICJzdHlsZSI6ICJrbm9iIiB9LHsgInVuaXQiOiAicyIgfV0sImluaXQiOiAwLjEsIm1pbiI6IDAsIm1heCI6IDAuMywic3RlcCI6IDAuMDF9LHsidHlwZSI6ICJ2c2xpZGVyIiwibGFiZWwiOiAiTm9pc2UgR2F0ZSIsImFkZHJlc3MiOiAiL0RlYWRHYXRlV2l0aFBhcmFtcy9Ob2lzZV9HYXRlIiwiaW5kZXgiOiAzODgsIm1ldGEiOiBbeyAic3R5bGUiOiAia25vYiIgfV0sImluaXQiOiAtMTIwLCJtaW4iOiAtMTIwLCJtYXgiOiAwLCJzdGVwIjogMC4wMDF9LHsidHlwZSI6ICJ2c2xpZGVyIiwibGFiZWwiOiAiUmVsZWFzZSIsImFkZHJlc3MiOiAiL0RlYWRHYXRlV2l0aFBhcmFtcy9SZWxlYXNlIiwiaW5kZXgiOiA0LCJtZXRhIjogW3sgInN0eWxlIjogImtub2IiIH0seyAidW5pdCI6ICJzIiB9XSwiaW5pdCI6IDAuMDIsIm1pbiI6IDAsIm1heCI6IDAuMDQsInN0ZXAiOiAwLjAwMX1dfV19"; }

/*
 faust2wasm: GRAME 2017-2019
*/

'use strict';

if (typeof (AudioWorkletNode) === "undefined") {
    alert("AudioWorklet is not supported in this browser !")
}

class DeadGateWithParamsNode extends AudioWorkletNode {

    constructor(context, baseURL, options) {
        super(context, 'DeadGateWithParams', options);

        this.baseURL = baseURL;
        this.json = options.processorOptions.json;
        this.json_object = JSON.parse(this.json);

        // JSON parsing functions
        this.parse_ui = function (ui, obj) {
            for (var i = 0; i < ui.length; i++) {
                this.parse_group(ui[i], obj);
            }
        }

        this.parse_group = function (group, obj) {
            if (group.items) {
                this.parse_items(group.items, obj);
            }
        }

        this.parse_items = function (items, obj) {
            for (var i = 0; i < items.length; i++) {
                this.parse_item(items[i], obj);
            }
        }

        this.parse_item = function (item, obj) {
            if (item.type === "vgroup"
                || item.type === "hgroup"
                || item.type === "tgroup") {
                this.parse_items(item.items, obj);
            } else if (item.type === "hbargraph"
                || item.type === "vbargraph") {
                // Keep bargraph adresses
                obj.outputs_items.push(item.address);
            } else if (item.type === "vslider"
                || item.type === "hslider"
                || item.type === "button"
                || item.type === "checkbox"
                || item.type === "nentry") {
                // Keep inputs adresses
                obj.inputs_items.push(item.address);
                obj.descriptor.push(item);
                // Decode MIDI
                if (item.meta !== undefined) {
                    for (var i = 0; i < item.meta.length; i++) {
                        if (item.meta[i].midi !== undefined) {
                            if (item.meta[i].midi.trim() === "pitchwheel") {
                                obj.fPitchwheelLabel.push({
                                    path: item.address,
                                    min: parseFloat(item.min),
                                    max: parseFloat(item.max)
                                });
                            } else if (item.meta[i].midi.trim().split(" ")[0] === "ctrl") {
                                obj.fCtrlLabel[parseInt(item.meta[i].midi.trim().split(" ")[1])]
                                    .push({
                                        path: item.address,
                                        min: parseFloat(item.min),
                                        max: parseFloat(item.max)
                                    });
                            }
                        }
                    }
                }
                // Define setXXX/getXXX, replacing '/c' with 'C' everywhere in the string
                var set_name = "set" + item.address;
                var get_name = "get" + item.address;
                set_name = set_name.replace(/\/./g, (x) => { return x.substr(1, 1).toUpperCase(); });
                get_name = get_name.replace(/\/./g, (x) => { return x.substr(1, 1).toUpperCase(); });
                obj[set_name] = (val) => { obj.setParamValue(item.address, val); };
                obj[get_name] = () => { return obj.getParamValue(item.address); };
                //console.log(set_name);
                //console.log(get_name);
            }
        }

        this.output_handler = null;

        // input/output items
        this.inputs_items = [];
        this.outputs_items = [];
        this.descriptor = [];

        // MIDI
        this.fPitchwheelLabel = [];
        this.fCtrlLabel = new Array(128);
        for (var i = 0; i < this.fCtrlLabel.length; i++) { this.fCtrlLabel[i] = []; }

        // Parse UI
        this.parse_ui(this.json_object.ui, this);

        // Set message handler
        this.port.onmessage = this.handleMessage.bind(this);
        try {
            if (this.parameters) this.parameters.forEach(p => p.automationRate = "k-rate");
        } catch (e) { }
    }

    // To be called by the message port with messages coming from the processor
    handleMessage(event) {
        var msg = event.data;
        if (this.output_handler) {
            this.output_handler(msg.path, msg.value);
        }
    }

    // Public API

    /**
     * Destroy the node, deallocate resources.
     */
    destroy() {
        this.port.postMessage({ type: "destroy" });
        this.port.close();
    }

    /**
     *  Returns a full JSON description of the DSP.
     */
    getJSON() {
        return this.json;
    }

    // For WAP
    async getMetadata() {
        return new Promise(resolve => {
            let real_url = (this.baseURL === "") ? "main.json" : (this.baseURL + "/main.json");
            fetch(real_url).then(responseJSON => {
                return responseJSON.json();
            }).then(json => {
                resolve(json);
            })
        });
    }

    /**
     *  Set the control value at a given path.
     *
     * @param path - a path to the control
     * @param val - the value to be set
     */
    setParamValue(path, val) {
        // Needed for sample accurate control
        this.parameters.get(path).setValueAtTime(val, 0);
    }

    // For WAP
    setParam(path, val) {
        // Needed for sample accurate control
        this.parameters.get(path).setValueAtTime(val, 0);
    }

    /**
     *  Get the control value at a given path.
     *
     * @return the current control value
     */
    getParamValue(path) {
        return this.parameters.get(path).value;
    }

    // For WAP
    getParam(path) {
        return this.parameters.get(path).value;
    }

    /**
     * Setup a control output handler with a function of type (path, value)
     * to be used on each generated output value. This handler will be called
     * each audio cycle at the end of the 'compute' method.
     *
     * @param handler - a function of type function(path, value)
     */
    setOutputParamHandler(handler) {
        this.output_handler = handler;
    }

    /**
     * Get the current output handler.
     */
    getOutputParamHandler() {
        return this.output_handler;
    }

    getNumInputs() {
        return parseInt(this.json_object.inputs);
    }

    getNumOutputs() {
        return parseInt(this.json_object.outputs);
    }

    // For WAP
    inputChannelCount() {
        return parseInt(this.json_object.inputs);
    }

    outputChannelCount() {
        return parseInt(this.json_object.outputs);
    }

    /**
     * Returns an array of all input paths (to be used with setParamValue/getParamValue)
     */
    getParams() {
        return this.inputs_items;
    }

    // For WAP
    getDescriptor() {
        var desc = {};
        for (const item in this.descriptor) {
            if (this.descriptor.hasOwnProperty(item)) {
                if (this.descriptor[item].label != "bypass") {
                    desc = Object.assign({ [this.descriptor[item].label]: { minValue: this.descriptor[item].min, maxValue: this.descriptor[item].max, defaultValue: this.descriptor[item].init } }, desc);
                }
            }
        }
        return desc;
    }

    /**
     * Control change
     *
     * @param channel - the MIDI channel (0..15, not used for now)
     * @param ctrl - the MIDI controller number (0..127)
     * @param value - the MIDI controller value (0..127)
     */
    ctrlChange(channel, ctrl, value) {
        if (this.fCtrlLabel[ctrl] !== []) {
            for (var i = 0; i < this.fCtrlLabel[ctrl].length; i++) {
                var path = this.fCtrlLabel[ctrl][i].path;
                this.setParamValue(path, DeadGateWithParamsNode.remap(value, 0, 127, this.fCtrlLabel[ctrl][i].min, this.fCtrlLabel[ctrl][i].max));
                if (this.output_handler) {
                    this.output_handler(path, this.getParamValue(path));
                }
            }
        }
    }

    /**
     * PitchWeel
     *
     * @param channel - the MIDI channel (0..15, not used for now)
     * @param value - the MIDI controller value (0..16383)
     */
    pitchWheel(channel, wheel) {
        for (var i = 0; i < this.fPitchwheelLabel.length; i++) {
            var pw = this.fPitchwheelLabel[i];
            this.setParamValue(pw.path, DeadGateWithParamsNode.remap(wheel, 0, 16383, pw.min, pw.max));
            if (this.output_handler) {
                this.output_handler(pw.path, this.getParamValue(pw.path));
            }
        }
    }

    /**
     * Generic MIDI message handler.
     */
    midiMessage(data) {
        var cmd = data[0] >> 4;
        var channel = data[0] & 0xf;
        var data1 = data[1];
        var data2 = data[2];

        if (channel === 9) {
            return;
        } else if (cmd === 11) {
            this.ctrlChange(channel, data1, data2);
        } else if (cmd === 14) {
            this.pitchWheel(channel, (data2 * 128.0 + data1));
        }
    }

    // For WAP
    onMidi(data) {
        midiMessage(data);
    }

    /**
     * @returns {Object} describes the path for each available param and its current value
     */
    async getState() {
        var params = new Object();
        for (let i = 0; i < this.getParams().length; i++) {
            Object.assign(params, { [this.getParams()[i]]: `${this.getParam(this.getParams()[i])}` });
        }
        return new Promise(resolve => { resolve(params) });
    }

    /**
     * Sets each params with the value indicated in the state object
     * @param {Object} state 
     */
    async setState(state) {
        return new Promise(resolve => {
            for (const param in state) {
                if (state.hasOwnProperty(param)) this.setParam(param, state[param]);
            }
            try {
                this.gui.setAttribute('state', JSON.stringify(state));
            } catch (error) {
                console.warn("Plugin without gui or GUI not defined", error);
            }
            resolve(state);
        })
    }

    /**
     * A different call closer to the preset management
     * @param {Object} patch to assign as a preset to the node
     */
    setPatch(patch) {
        this.setState(this.presets[patch])
    }

    static remap(v, mn0, mx0, mn1, mx1) {
        return (1.0 * (v - mn0) / (mx0 - mn0)) * (mx1 - mn1) + mn1;
    }

}

// Factory class
class DeadGateWithParams {

    static fWorkletProcessors;

    /**
     * Factory constructor.
     *
     * @param context - the audio context
     * @param baseURL - the baseURL of the plugin folder
     */
    constructor(context, baseURL = "") {
        console.log("baseLatency " + context.baseLatency);
        console.log("outputLatency " + context.outputLatency);
        console.log("sampleRate " + context.sampleRate);

        this.context = context;
        this.baseURL = baseURL;
        this.pathTable = [];

        this.fWorkletProcessors = this.fWorkletProcessors || [];
    }

    heap2Str(buf) {
        let str = "";
        let i = 0;
        while (buf[i] !== 0) {
            str += String.fromCharCode(buf[i++]);
        }
        return str;
    }

    /**
     * Load additionnal resources to prepare the custom AudioWorkletNode. Returns a promise to be used with the created node.
     */
    async load() {
        try {
            const importObject = {
                env: {
                    memoryBase: 0,
                    tableBase: 0,
                    _abs: Math.abs,

                    // Float version
                    _acosf: Math.acos,
                    _asinf: Math.asin,
                    _atanf: Math.atan,
                    _atan2f: Math.atan2,
                    _ceilf: Math.ceil,
                    _cosf: Math.cos,
                    _expf: Math.exp,
                    _floorf: Math.floor,
                    _fmodf: (x, y) => x % y,
                    _logf: Math.log,
                    _log10f: Math.log10,
                    _max_f: Math.max,
                    _min_f: Math.min,
                    _remainderf: (x, y) => x - Math.round(x / y) * y,
                    _powf: Math.pow,
                    _roundf: Math.fround,
                    _sinf: Math.sin,
                    _sqrtf: Math.sqrt,
                    _tanf: Math.tan,
                    _acoshf: Math.acosh,
                    _asinhf: Math.asinh,
                    _atanhf: Math.atanh,
                    _coshf: Math.cosh,
                    _sinhf: Math.sinh,
                    _tanhf: Math.tanh,

                    // Double version
                    _acos: Math.acos,
                    _asin: Math.asin,
                    _atan: Math.atan,
                    _atan2: Math.atan2,
                    _ceil: Math.ceil,
                    _cos: Math.cos,
                    _exp: Math.exp,
                    _floor: Math.floor,
                    _fmod: (x, y) => x % y,
                    _log: Math.log,
                    _log10: Math.log10,
                    _max_: Math.max,
                    _min_: Math.min,
                    _remainder: (x, y) => x - Math.round(x / y) * y,
                    _pow: Math.pow,
                    _round: Math.fround,
                    _sin: Math.sin,
                    _sqrt: Math.sqrt,
                    _tan: Math.tan,
                    _acosh: Math.acosh,
                    _asinh: Math.asinh,
                    _atanh: Math.atanh,
                    _cosh: Math.cosh,
                    _sinh: Math.sinh,
                    _tanh: Math.tanh,

                    table: new WebAssembly.Table({ initial: 0, element: "anyfunc" })
                }
            };

            let real_url = (this.baseURL === "") ? "DeadGateWithParams.wasm" : (this.baseURL + "/DeadGateWithParams.wasm");
            const dspFile = await fetch(real_url);
            const dspBuffer = await dspFile.arrayBuffer();
            const dspModule = await WebAssembly.compile(dspBuffer);
            const dspInstance = await WebAssembly.instantiate(dspModule, importObject);

            let HEAPU8 = new Uint8Array(dspInstance.exports.memory.buffer);
            let json = this.heap2Str(HEAPU8);
            let json_object = JSON.parse(json);
            let options = { wasm_module: dspModule, json: json };

            if (this.fWorkletProcessors.indexOf(name) === -1) {
                try {
                    let re = /JSON_STR/g;
                    let DeadGateWithParamsProcessorString1 = DeadGateWithParamsProcessorString.replace(re, json);
                    let real_url = window.URL.createObjectURL(new Blob([DeadGateWithParamsProcessorString1], { type: 'text/javascript' }));
                    await this.context.audioWorklet.addModule(real_url);
                    // Keep the DSP name
                    console.log("Keep the DSP name");
                    this.fWorkletProcessors.push(name);
                } catch (e) {
                    console.error(e);
                    console.error("Faust " + this.name + " cannot be loaded or compiled");
                    return null;
                }
            }
            this.node = new DeadGateWithParamsNode(this.context, this.baseURL,
                {
                    numberOfInputs: (parseInt(json_object.inputs) > 0) ? 1 : 0,
                    numberOfOutputs: (parseInt(json_object.outputs) > 0) ? 1 : 0,
                    channelCount: Math.max(1, parseInt(json_object.inputs)),
                    outputChannelCount: [parseInt(json_object.outputs)],
                    channelCountMode: "explicit",
                    channelInterpretation: "speakers",
                    processorOptions: options
                });
            this.node.onprocessorerror = () => { console.log('An error from DeadGateWithParams-processor was detected.'); }
            return (this.node);
        } catch (e) {
            console.error(e);
            console.error("Faust " + this.name + " cannot be loaded or compiled");
            return null;
        }
    }

    async loadGui() {
        return new Promise((resolve, reject) => {
            try {
                // DO THIS ONLY ONCE. If another instance has already been added, do not add the html file again
                let real_url = (this.baseURL === "") ? "main.html" : (this.baseURL + "/main.html");
                if (!this.linkExists(real_url)) {
                    // LINK DOES NOT EXIST, let's add it to the document
                    var link = document.createElement('link');
                    link.rel = 'import';
                    link.href = real_url;
                    document.head.appendChild(link);
                    link.onload = (e) => {
                        // the file has been loaded, instanciate GUI
                        // and get back the HTML elem
                        // HERE WE COULD REMOVE THE HARD CODED NAME
                        var element = createDeadGateWithParamsGUI(this.node);
                        resolve(element);
                    }
                } else {
                    // LINK EXIST, WE AT LEAST CREATED ONE INSTANCE PREVIOUSLY
                    // so we can create another instance
                    var element = createDeadGateWithParamsGUI(this.node);
                    resolve(element);
                }
            } catch (e) {
                console.log(e);
                reject(e);
            }
        });
    };

    linkExists(url) {
        return document.querySelectorAll(`link[href="${url}"]`).length > 0;
    }
}

// Template string for AudioWorkletProcessor

let DeadGateWithParamsProcessorString = `

    'use strict';

    // Monophonic Faust DSP
    class DeadGateWithParamsProcessor extends AudioWorkletProcessor {
        
        // JSON parsing functions
        static parse_ui(ui, obj, callback)
        {
            for (var i = 0; i < ui.length; i++) {
                DeadGateWithParamsProcessor.parse_group(ui[i], obj, callback);
            }
        }
        
        static parse_group(group, obj, callback)
        {
            if (group.items) {
                DeadGateWithParamsProcessor.parse_items(group.items, obj, callback);
            }
        }
        
        static parse_items(items, obj, callback)
        {
            for (var i = 0; i < items.length; i++) {
                callback(items[i], obj, callback);
            }
        }
        
        static parse_item1(item, obj, callback)
        {
            if (item.type === "vgroup"
                || item.type === "hgroup"
                || item.type === "tgroup") {
                DeadGateWithParamsProcessor.parse_items(item.items, obj, callback);
            } else if (item.type === "hbargraph"
                       || item.type === "vbargraph") {
                // Nothing
            } else if (item.type === "vslider"
                       || item.type === "hslider"
                       || item.type === "button"
                       || item.type === "checkbox"
                       || item.type === "nentry") {
                obj.push({ name: item.address,
                         defaultValue: item.init,
                         minValue: item.min,
                         maxValue: item.max });
            }
        }
        
        static parse_item2(item, obj, callback)
        {
            if (item.type === "vgroup"
                || item.type === "hgroup"
                || item.type === "tgroup") {
                DeadGateWithParamsProcessor.parse_items(item.items, obj, callback);
            } else if (item.type === "hbargraph"
                       || item.type === "vbargraph") {
                // Keep bargraph adresses
                obj.outputs_items.push(item.address);
                obj.pathTable[item.address] = parseInt(item.index);
            } else if (item.type === "vslider"
                       || item.type === "hslider"
                       || item.type === "button"
                       || item.type === "checkbox"
                       || item.type === "nentry") {
                // Keep inputs adresses
                obj.inputs_items.push(item.address);
                obj.pathTable[item.address] = parseInt(item.index);
            }
        }
     
        static get parameterDescriptors() 
        {
            // Analyse JSON to generate AudioParam parameters
            var params = [];
            DeadGateWithParamsProcessor.parse_ui(JSON.parse(\`JSON_STR\`).ui, params, DeadGateWithParamsProcessor.parse_item1);
            return params;
        }
       
        constructor(options)
        {
            super(options);
            this.running = true;
            
            const importObject = {
                    env: {
                        memoryBase: 0,
                        tableBase: 0,

                        // Integer version
                        _abs: Math.abs,

                        // Float version
                        _acosf: Math.acos,
                        _asinf: Math.asin,
                        _atanf: Math.atan,
                        _atan2f: Math.atan2,
                        _ceilf: Math.ceil,
                        _cosf: Math.cos,
                        _expf: Math.exp,
                        _floorf: Math.floor,
                        _fmodf: function(x, y) { return x % y; },
                        _logf: Math.log,
                        _log10f: Math.log10,
                        _max_f: Math.max,
                        _min_f: Math.min,
                        _remainderf: function(x, y) { return x - Math.round(x/y) * y; },
                        _powf: Math.pow,
                        _roundf: Math.fround,
                        _sinf: Math.sin,
                        _sqrtf: Math.sqrt,
                        _tanf: Math.tan,
                        _acoshf: Math.acosh,
                        _asinhf: Math.asinh,
                        _atanhf: Math.atanh,
                        _coshf: Math.cosh,
                        _sinhf: Math.sinh,
                        _tanhf: Math.tanh,

                        // Double version
                        _acos: Math.acos,
                        _asin: Math.asin,
                        _atan: Math.atan,
                        _atan2: Math.atan2,
                        _ceil: Math.ceil,
                        _cos: Math.cos,
                        _exp: Math.exp,
                        _floor: Math.floor,
                        _fmod: function(x, y) { return x % y; },
                        _log: Math.log,
                        _log10: Math.log10,
                        _max_: Math.max,
                        _min_: Math.min,
                        _remainder:function(x, y) { return x - Math.round(x/y) * y; },
                        _pow: Math.pow,
                        _round: Math.fround,
                        _sin: Math.sin,
                        _sqrt: Math.sqrt,
                        _tan: Math.tan,
                        _acosh: Math.acosh,
                        _asinh: Math.asinh,
                        _atanh: Math.atanh,
                        _cosh: Math.cosh,
                        _sinh: Math.sinh,
                        _tanh: Math.tanh,

                        table: new WebAssembly.Table({ initial: 0, element: 'anyfunc' })
                    }
            };
            
            this.DeadGateWithParams_instance = new WebAssembly.Instance(options.processorOptions.wasm_module, importObject);
            this.json_object = JSON.parse(options.processorOptions.json);
         
            this.output_handler = function(path, value) { this.port.postMessage({ path: path, value: value }); };
            
            this.ins = null;
            this.outs = null;

            this.dspInChannnels = [];
            this.dspOutChannnels = [];

            this.numIn = parseInt(this.json_object.inputs);
            this.numOut = parseInt(this.json_object.outputs);

            // Memory allocator
            this.ptr_size = 4;
            this.sample_size = 4;
            this.integer_size = 4;
            
            this.factory = this.DeadGateWithParams_instance.exports;
            this.HEAP = this.DeadGateWithParams_instance.exports.memory.buffer;
            this.HEAP32 = new Int32Array(this.HEAP);
            this.HEAPF32 = new Float32Array(this.HEAP);

            // Warning: keeps a ref on HEAP in Chrome and prevent proper GC
            //console.log(this.HEAP);
            //console.log(this.HEAP32);
            //console.log(this.HEAPF32);

            // bargraph
            this.outputs_timer = 5;
            this.outputs_items = [];

            // input items
            this.inputs_items = [];
        
            // Start of HEAP index

            // DSP is placed first with index 0. Audio buffer start at the end of DSP.
            this.audio_heap_ptr = parseInt(this.json_object.size);

            // Setup pointers offset
            this.audio_heap_ptr_inputs = this.audio_heap_ptr;
            this.audio_heap_ptr_outputs = this.audio_heap_ptr_inputs + (this.numIn * this.ptr_size);

            // Setup buffer offset
            this.audio_heap_inputs = this.audio_heap_ptr_outputs + (this.numOut * this.ptr_size);
            this.audio_heap_outputs = this.audio_heap_inputs + (this.numIn * NUM_FRAMES * this.sample_size);
            
            // Start of DSP memory : DSP is placed first with index 0
            this.dsp = 0;

            this.pathTable = [];
         
            // Send output values to the AudioNode
            this.update_outputs = function ()
            {
                if (this.outputs_items.length > 0 && this.output_handler && this.outputs_timer-- === 0) {
                    this.outputs_timer = 5;
                    for (var i = 0; i < this.outputs_items.length; i++) {
                        this.output_handler(this.outputs_items[i], this.HEAPF32[this.pathTable[this.outputs_items[i]] >> 2]);
                    }
                }
            }
            
            this.initAux = function ()
            {
                var i;
                
                if (this.numIn > 0) {
                    this.ins = this.audio_heap_ptr_inputs;
                    for (i = 0; i < this.numIn; i++) {
                        this.HEAP32[(this.ins >> 2) + i] = this.audio_heap_inputs + ((NUM_FRAMES * this.sample_size) * i);
                    }
                    
                    // Prepare Ins buffer tables
                    var dspInChans = this.HEAP32.subarray(this.ins >> 2, (this.ins + this.numIn * this.ptr_size) >> 2);
                    for (i = 0; i < this.numIn; i++) {
                        this.dspInChannnels[i] = this.HEAPF32.subarray(dspInChans[i] >> 2, (dspInChans[i] + NUM_FRAMES * this.sample_size) >> 2);
                    }
                }
                
                if (this.numOut > 0) {
                    this.outs = this.audio_heap_ptr_outputs;
                    for (i = 0; i < this.numOut; i++) {
                        this.HEAP32[(this.outs >> 2) + i] = this.audio_heap_outputs + ((NUM_FRAMES * this.sample_size) * i);
                    }
                    
                    // Prepare Out buffer tables
                    var dspOutChans = this.HEAP32.subarray(this.outs >> 2, (this.outs + this.numOut * this.ptr_size) >> 2);
                    for (i = 0; i < this.numOut; i++) {
                        this.dspOutChannnels[i] = this.HEAPF32.subarray(dspOutChans[i] >> 2, (dspOutChans[i] + NUM_FRAMES * this.sample_size) >> 2);
                    }
                }
                
                // Parse UI
                DeadGateWithParamsProcessor.parse_ui(this.json_object.ui, this, DeadGateWithParamsProcessor.parse_item2);
                
                // Init DSP
                this.factory.init(this.dsp, sampleRate); // 'sampleRate' is defined in AudioWorkletGlobalScope  
            }

            this.setParamValue = function (path, val)
            {
                this.HEAPF32[this.pathTable[path] >> 2] = val;
            }

            this.getParamValue = function (path)
            {
                return this.HEAPF32[this.pathTable[path] >> 2];
            }

            // Init resulting DSP
            this.initAux();
        }
        
        process(inputs, outputs, parameters) 
        {
            var input = inputs[0];
            var output = outputs[0];
            
            // Check inputs
            if (this.numIn > 0 && (!input || !input[0] || input[0].length === 0)) {
                //console.log("Process input error");
                return true;
            }
            // Check outputs
            if (this.numOut > 0 && (!output || !output[0] || output[0].length === 0)) {
                //console.log("Process output error");
                return true;
            }
            
            // Copy inputs
            if (input !== undefined) {
                for (var chan = 0; chan < Math.min(this.numIn, input.length); ++chan) {
                    var dspInput = this.dspInChannnels[chan];
                    dspInput.set(input[chan]);
                }
            }
            
            /*
            TODO: sample accurate control change is not yet handled
            When no automation occurs, params[i][1] has a length of 1,
            otherwise params[i][1] has a length of NUM_FRAMES with possible control change each sample
            */
            
            // Update controls
            for (const path in parameters) {
                const paramArray = parameters[path];
                this.setParamValue(path, paramArray[0]);
            }
        
          	// Compute
            try {
                this.factory.compute(this.dsp, NUM_FRAMES, this.ins, this.outs);
            } catch(e) {
                console.log("ERROR in compute (" + e + ")");
            }
            
            // Update bargraph
            this.update_outputs();
            
            // Copy outputs
            if (output !== undefined) {
                for (var chan = 0; chan < Math.min(this.numOut, output.length); ++chan) {
                    var dspOutput = this.dspOutChannnels[chan];
                    output[chan].set(dspOutput);
                }
            }
            
            return this.running;
    	}
        
        handleMessage(event)
        {
            var msg = event.data;
            switch (msg.type) {
                case "destroy": this.running = false; break;
            }
        }
    }

    // Globals
    const NUM_FRAMES = 128;
    try {
        registerProcessor('DeadGateWithParams', DeadGateWithParamsProcessor);
    } catch (error) {
        console.warn(error);
    }
`;

const dspName2 = "DeadGateWithParams";

// WAP factory or npm package module
if (typeof module === "undefined") {
    window.DeadGateWithParams = DeadGateWithParams;
    window.FaustDeadGateWithParams = DeadGateWithParams;
    window[dspName2] = DeadGateWithParams;
} else {
    module.exports = { DeadGateWithParams };
}
