export function buildAssetTree(container, assets, {search='', selectedId='', onSelect, renderAsset, renderGroup, isFavorite, toggleFavorite}={}) {
  const query=search.trim().toLowerCase(); const visible=assets.filter(a=>!query||[a.displayName,a.filename,a.relativePath,JSON.stringify(a.metadata||'')].some(v=>String(v||'').toLowerCase().includes(query)));
  const roots={}; for(const asset of visible){let node=roots;for(const group of asset.groups||[]){node=node[group]??={};} (node.__assets??=[]).push(asset);}
  const containsSelected=(node)=>(node.__assets||[]).some(asset=>asset.id===selectedId)||Object.keys(node).filter(key=>key!=='__assets').some(key=>containsSelected(node[key]));
  const favoriteButton=(asset)=>{const button=document.createElement('button');button.type='button';button.className='favoriteToggle';const active=Boolean(isFavorite?.(asset));button.classList.toggle('active',active);button.setAttribute('aria-label',`${active?'Remove from':'Add to'} favorites: ${asset.displayName||asset.filename}`);button.title=active?'Remove from favorites':'Add to favorites';button.textContent=active?'★':'☆';button.onclick=(event)=>{event.stopPropagation();toggleFavorite?.(asset);};return button;};
  container.replaceChildren(); const render=(node,parent)=>{for(const key of Object.keys(node).filter(k=>k!=='__assets').sort()){const branch=node[key];const childGroups=Object.keys(branch).filter(k=>k!=='__assets');const groupElement=!childGroups.length&&branch.__assets?.length?renderGroup?.({name:key,assets:branch.__assets,selectedId,onSelect,isFavorite,toggleFavorite,favoriteButton}):null;if(groupElement){parent.append(groupElement);continue;}const details=document.createElement('details');details.open=!!query||containsSelected(branch);const summary=document.createElement('summary');summary.textContent=key;details.append(summary);render(branch,details);parent.append(details);}for(const asset of node.__assets||[]){const button=renderAsset?.(asset)||document.createElement('button');button.type='button';button.classList.add('asset-entry');button.dataset.assetId=asset.id;if(!button.childNodes.length)button.textContent=asset.displayName;if(asset.id===selectedId)button.classList.add('selected');button.title=asset.relativePath;button.onclick=()=>onSelect(asset);if(toggleFavorite){const row=document.createElement('div');row.className='assetRow';row.append(button,favoriteButton(asset));parent.append(row);}else parent.append(button);}};render(roots,container);
}
export function addExternalAsset(assets, asset){if(!assets.some(a=>a.id===asset.id))assets.push(asset);return assets.find(a=>a.id===asset.id);}

export function factoryAssetUrl(baseUrl, directory, relativePath) {
  const segments=String(relativePath||'').replaceAll('\\','/').split('/');
  if(!segments.length||segments.some(segment=>!segment||segment==='.'||segment==='..'))throw new Error(`Invalid Factory asset path: ${relativePath}`);
  return new URL(`${encodeURIComponent(directory)}/${segments.map(segment=>encodeURIComponent(segment)).join('/')}`,baseUrl);
}
