const getCabinetProcessor=(moduleId)=>{const scope=globalThis;const {WamProcessor,WamParameterInfo}=scope.webAudioModules.getModuleScope(moduleId);const Q=128,CAP=16384;
class CabinetProcessor extends WamProcessor {
 constructor(options){super(options);this._module=options.processorOptions.wasmModule;this._handle=0;this._ready=false;this._compensation=1;this._smoothedCompensation=1;this._smoothing=1-Math.exp(-1/(.02*scope.sampleRate));this._timings=new Float64Array(CAP);this._count=0;this._write=0;this._calls=0;this._failures=0;this._diagnostic=false;}
 _generateWamParameterInfo(){return {levelMatch:new WamParameterInfo('levelMatch',{type:'boolean',label:'Level Match',defaultValue:1}),irTrim:new WamParameterInfo('irTrim',{label:'IR Trim',defaultValue:0,minValue:-12,maxValue:12,units:'dB'}),outputGain:new WamParameterInfo('outputGain',{label:'Output Gain',defaultValue:0,minValue:-24,maxValue:12,units:'dB'}),bypass:new WamParameterInfo('bypass',{type:'boolean',label:'Bypass',defaultValue:0})};}
 _initialize(){super._initialize();const noop=()=>0;this._instance=new WebAssembly.Instance(this._module,{env:{emscripten_notify_memory_growth:noop},wasi_snapshot_preview1:{fd_seek:noop,fd_write:noop,fd_read:noop,fd_close:noop,environ_sizes_get:noop,environ_get:noop}});this._exports=this._instance.exports;this._memory=this._exports.memory;this._exports._initialize();this._handle=this._exports.cabinet_create(scope.sampleRate);}
 async _onMessage(message){const d=message.data;if(!d.cabinetRequest)return super._onMessage(message);const r={cabinetResponse:d.cabinetRequest,requestId:d.requestId,ok:false};try{if(d.cabinetRequest==='load')r.content=this._load(d.samples,d.name,d.compensation);else if(d.cabinetRequest==='diagnostic/start'){this._diagnostic=true;this._count=this._write=this._calls=this._failures=0;r.content=true;}else if(d.cabinetRequest==='diagnostic/stop')r.content=this._stop();else if(d.cabinetRequest==='status')r.content={ready:this._ready,calls:this._calls,failures:this._failures,irLength:this._exports.cabinet_ir_length(this._handle),compensation:this._compensation};r.ok=true;}catch(e){r.error=String(e?.message||e);}this.port.postMessage(r);}
 _load(buffer,name,compensation){const samples=new Float32Array(buffer);const p=this._exports.malloc(samples.byteLength);if(!p)throw Error('Insufficient WASM memory');new Float32Array(this._memory.buffer,p,samples.length).set(samples);const ok=this._exports.cabinet_load_ir(this._handle,p,samples.length);this._exports.free(p);if(!ok)throw Error('Cabinet IR load failed');this._inputPtr=this._exports.cabinet_input_buffer(this._handle);this._outputPtr=this._exports.cabinet_output_buffer(this._handle);this._input=new Float32Array(this._memory.buffer,this._inputPtr,Q);this._output=new Float32Array(this._memory.buffer,this._outputPtr,Q);this._compensation=Number.isFinite(compensation)&&compensation>0?compensation:1;this._ready=true;return {name,length:samples.length,sampleRate:scope.sampleRate,compensation:this._compensation};}
 _stop(){this._diagnostic=false;const n=Math.min(this._count,CAP),v=this._timings.slice(0,n);v.sort();let sum=0,misses=0;const deadline=128000/scope.sampleRate;for(let i=0;i<n;i++){sum+=v[i];if(v[i]>=deadline)misses++;}return {samples:n,averageMs:n?sum/n:0,p95Ms:n?v[Math.floor((n-1)*.95)]:0,maximumMs:n?v[n-1]:0,deadlineMs:deadline,deadlineMisses:misses,calls:this._calls,failures:this._failures};}
 _process(start,end,inputs,outputs){const out=outputs[0]?.[0];if(!out)return;const input=inputs[0]?.[0];const bypass=this._parameterInterpolators.bypass.values[start]>=.5;const began=this._diagnostic?Date.now():0;if(!input){for(let i=start;i<end;i++)out[i]=0;}else if(bypass||!this._ready){for(let i=start;i<end;i++)out[i]=input[i];}else{const frames=end-start;for(let i=0;i<frames;i++)this._input[i]=input[start+i];const ok=this._exports.cabinet_process(this._handle,this._inputPtr,this._outputPtr,frames);this._calls++;if(!ok)this._failures++;const levelMatch=this._parameterInterpolators.levelMatch,irTrim=this._parameterInterpolators.irTrim,outputGain=this._parameterInterpolators.outputGain;for(let i=0;i<frames;i++){const n=start+i,target=(levelMatch.values[n]>=.5?this._compensation:1)*10**(irTrim.values[n]/20);this._smoothedCompensation+=(target-this._smoothedCompensation)*this._smoothing;const trim=10**(outputGain.values[n]/20);out[n]=ok?this._output[i]*this._smoothedCompensation*trim:0;}}if(this._diagnostic){this._timings[this._write]=Date.now()-began;this._write=(this._write+1)&(CAP-1);if(this._count<CAP)this._count++;}}
 destroy(){if(this._handle)this._exports.cabinet_destroy(this._handle);this._handle=0;super.destroy();}
}
scope.registerProcessor(moduleId,CabinetProcessor);return CabinetProcessor;};export default getCabinetProcessor;
